### ISSUE TITLE
Issue to retrieve  MdatpDeviceId info when running Isolate-MDEMachine playbook

### ISSUE THREAD

**Issue by mitreattack** [Azure/Azure-Sentinel#10158]
**Describe the bug**
When the playbook has been triggered by incidents sometimes MdatpDeviceId info can be seen and sometimes can't, even the devices from defender environment in the same policy group, can you please let me know what the condition have to be set/matched there then the playbook can retrieve the MdatpDeviceId info. please refer to the screenshot below.

**Expected behavior**
MdatpDeviceId info can be retrieved, then to be used to isolate the device.

**Screenshots**

![image](https://github.com/Azure/Azure-Sentinel/assets/88364896/1b0da423-96dc-4612-a7bb-a420c022d172)

![image](https://github.com/Azure/Azure-Sentinel/assets/88364896/bbc0b7f1-9c62-427d-b468-c5ab21c6cd32)

Thanks

**Comment by v-sudkharat** [comment]
Hi @mitreattack, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 21-03-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @mitreattack, We have checked this issue in our end, by trigger the playbook with Incident which having the Host Entity. 
In below screenshot, you can see we are getting the filed - `MdatpDeviceId` with its value, which playbook fetch from data which we are having in our workspace: - 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/5b7026ab-0ad6-4640-8ff6-5569816878c6)

 Due to unauthorized permission, the Action - Isolate machine not executed successfully and it move for 2nd condition which is adding comment- 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/b36f3108-7eb7-462a-ba20-86ff5e7fdb14)

2nd flow: - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/ff804474-3698-41b7-9e1e-411318463e13)

 Here, we have triggered the same playbook, with different data source where the Host does not have the required value for it, so due to that the Output does not showing the - `MdatpDeviceId` and the its value for it.  
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/90600ffd-31be-4ea4-a47b-33fd28789ccf)

So, if you keep the default playbook configuration and run it, its works without any issue. Just need to verify the source from where the playbook get triggers and it have those details for it. 
Ex - In below screenshot, The source(Incident/AnayticRule) having the required field for playbook which is. ( `MdatpDeviceId` ) and when playbook triggered the value gets fetch and continue the flow - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/244b2bec-a1ee-4592-a451-384d9c309e41)

Please let us know, if you still have any queries on this. 
Thanks!

**Comment by v-sudkharat** [comment]
Hi @mitreattack, closing this issue as no queries on this. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
