### ISSUE TITLE
Does Sentinel support AWS VPC Flos Logs with PerHourPartition enabled

### ISSUE THREAD

**Issue by rkitron** [Azure/Azure-Sentinel#10203]
Hello,

Does Sentinel support this settings ?

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-flow-logs.html

Thanks

**Comment by v-muuppugund** [comment]
HI @rkitron ,Could you please share more details what is the problem /requirement in detail,so will proceed further

**Comment by v-sudkharat** [comment]
Hi @rkitron, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 03-04-2024 date, we will be closing this issue. 		
Thanks!

**Comment by v-muuppugund** [comment]
Hi @rkitron ,Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/10203) as per our standard operating procedures. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation!
