### ISSUE TITLE
Training Lab guide fails with error to deploy metadata

### ISSUE THREAD

**Issue by javiersoriano** [Azure/Azure-Sentinel#10220]
When trying to deploy Training Lab solution from Content Hub, the following error is displayed:

![image](https://github.com/Azure/Azure-Sentinel/assets/13329585/d9f46ee0-b619-4a48-bb9e-52b5bdc2dff2)

![image](https://github.com/Azure/Azure-Sentinel/assets/13329585/87b80a2d-83d9-4c42-a9da-7af1e5faa4ae)

![image](https://github.com/Azure/Azure-Sentinel/assets/13329585/b8f47049-635b-4640-9a5a-25efc2ac9ea9)

Can you asisst?

**Comment by v-sudkharat** [comment]
Hi @javiersoriano, we are reaching out to the concerned team for this issue, once we receive an update on this, we will update you.
Thanks!

**Comment by AttacktheSOC** [comment]
Hi @v-sudkharat I took a quick jab at it in my lab and pulled down the template.json after I received the same failure. 

It looks like the parentId was expecting a fully qualified resource id. After some poking around I was able to deploy a custom template and it seems that the parentId, contentId and properties.source.sourceId all need to be changed from:

"[variables('_sourceId')]"

 to:
"[extensionResourceId(resourceId('Microsoft.OperationalInsights/workspaces', parameters('workspace')), 'Microsoft.SecurityInsights/metadata', variables('_sourceId')) ]"

Can confirm a full successful deployment after this change.

Hopefully this helps narrow things down for the team a bit.
Thanks!
- Dylan

**Comment by v-sudkharat** [comment]
Hi @AttacktheSOC, Thank you for sharing your observation with us. We have tested the template with your suggested solution, and the deployment completed successfully : - 

![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/bb1422c5-9fb8-4d7d-8171-6cc51c6eb279)

But, after deployment the solution does not show as installed in Content Hub, it may be due to the installation or sync not done correctly  : - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/30e466ca-07c1-462f-9dc3-db0bd274e1f2)

We have reached out to our respective backend team for this issue, and once we receive any update from them will update you.
Thanks again for your contribution. Please let us know if have any questions or won't to share any update on this. 

Thanks!

**Comment by AttacktheSOC** [comment]
Ahh so close, lol. Please let me know if I can help test anything, would be more than happy!

**Comment by v-sudkharat** [comment]
@AttacktheSOC, Sure. Thanks!

**Comment by v-sudkharat** [comment]
Hey @javiersoriano/ @AttacktheSOC, The issue has been resolved by our concern team, please redeploy the solution and let us know of you still having issue. Thanks! 
Sharing deployment screenshot: - 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/9d913ac6-383b-4853-9a5e-5a036f5a857d)

**Comment by javiersoriano** [comment]
It all works well now, Thanks!!
