### ISSUE TITLE
Typo in folder name: Azure-Sentinel/Parsers/SQLSever

### ISSUE THREAD

**Issue by SteveBurkettNZ** [Azure/Azure-Sentinel#10301]
**Describe the bug**
Folder name for the SQL Server parser has a typo.

**To Reproduce**
See path: https://github.com/Azure/Azure-Sentinel/tree/master/Parsers/SQLSever

**Expected behavior**
Should be: https://github.com/Azure/Azure-Sentinel/tree/master/Parsers/SQLServer

**Comment by v-sudkharat** [comment]
Hi @SteveBurkettNZ, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 19-04-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hey @SteveBurkettNZ, Thanks for highlighting this typo with us. The current folder path is linked to other solutions too. So due to that we have to keep this current path in repo. But we will make this typo correction in upcoming solution release. 
Closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
