### ISSUE TITLE
Threat Intelligence Solution missing the data connector - Premium Microsoft Defender Threat Intelligence

### ISSUE THREAD

**Issue by MikeP1375** [Azure/Azure-Sentinel#10460]
The Threat Intelligence solution 3.0.3 GitHub contain reports five data connectors - https://github.com/Azure/Azure-Sentinel/tree/master/Solutions/Threat%20Intelligence/Data%20Connectors.

The content solution inside Sentinel reports 4 data connectors not 5. The missing one is https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Threat%20Intelligence/Data%20Connectors/template_PremiumMicrosoftDefenderThreatIntelligence.json

Could you please investigate and fix the solution to report all the data connectors.

Thanks

Mike

**Comment by v-sudkharat** [comment]
Hi @MikeP1375, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 20-05-2024. Thanks!

**Comment by v-sudkharat** [comment]
Hi @MikeP1375, We have checked the data connector "[template_PremiumMicrosoftDefenderThreatIntelligence.json](https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Threat%20Intelligence/Data%20Connectors/template_PremiumMicrosoftDefenderThreatIntelligence.json)" currently it's in Private preview and not globally available yet. So due to that reasone it not added into the solution. 
But you can monitor our repo for the upcoming updates. So, closing this issue. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
