### ISSUE TITLE
Trend Micro Vision One (Function App) - 'extend' operator: Failed to resolve scalar expression named 'FileName_s'

### ISSUE THREAD

**Issue by hgtok** [Azure/Azure-Sentinel#10653]
**Describe the bug**
Error while creating rule from 'Create Incident for XDR Alerts' template.

**To Reproduce**
1. Go to Sentinel > Content hub  > Trend Vision One > Manage
2. Check 'Create Incident for XDR Alerts' > Create rule
3. Click on 'Next: Set rule logic'
4. See error 'extend' operator: Failed to resolve scalar expression named 'FileName_s'

**Expected behavior**
No errors and able to create rule 'Create Incident for XDR Alerts' in Sentinel.

**Screenshots**
![image](https://github.com/Azure/Azure-Sentinel/assets/11731575/335ff21c-cc72-41a3-8b29-522b4f6b8b3d)

**Additional context**
Multiple errors as attached. May be related to errors encountered in #10622

**Comment by v-sudkharat** [comment]
Hey @hgtok, this error you're getting after change which done in issue - https://github.com/Azure/Azure-Sentinel/issues/10622 Or it's from beginning?   
And also want to know could you please check for the data is receiving into the table - **TrendMicro_XDR_WORKBENCH_CL** 
If yes, please share the sample data with us so we can check it. Thanks!

**Comment by hgtok** [comment]
hi, this is a new setup. before #10622, there are no tables nor data in Sentinel.

After applying your given workaround in #10622, we saw the data being ingested.

However faced this issue, when trying to install the template rule from the Vision One solution.

Hope this explains

**Comment by v-sudkharat** [comment]
@hgtok, yes. you can share it on mail - v-sudkharat@microsoft.com

**Comment by v-sudkharat** [comment]
Hi @hgtok, We have reviewed the table data you shared with us via mail. This issue did not occur due to the changes we made in issue- https://github.com/Azure/Azure-Sentinel/issues/10622 (fixing packages issue), Upon analysis of your shared data, we found that the required columns were not created in the tables, which is why the Rule was not getting created.  
We request you to check the configuration in Trend Micro side, and we also have checked this solution, this solution is supported with Trend Micro Vision One However, we are not authorized to make any modifications to it. We kindly request that you raise an issue ticket with the Trend Micro Vision One support team. 
Sharing the Trend Micro Vision One support link -
Link - "https://success.trendmicro.com/dcx/s/?language=en_US"
Closing this issue from GitHub. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
