### ISSUE TITLE
(CyberSecurity Malaysia)

### ISSUE THREAD

**Issue by Hanzhafiz** [Azure/Azure-Sentinel#10926]
https://github.com/cloudflare/cloudflare-docs/blob/production/content%2Fruleset-engine%2Frules-language%2Fexpressions%2F_index.md

**Comment by Hanzhafiz** [comment]
https://github.com/cloudflare/cloudflare-docs/blob/production/content%2Fruleset-engine%2Frules-language%2Fexpressions%2F_index.md

**Comment by v-sudkharat** [comment]
Hi @Hanzhafiz, Thank you for flagging issue. I think you have incorrectly opened the issue in this repo, instead of Cloudflare repository -https://github.com/cloudflare/cloudflare-docs
Kindly check on the above-mentioned repo link where you can open the same. 
Closing this issue from this Sentinel repository. If you still need support for this issue, feel free to re-open it any time. Thank you for your co-operation.
