### ISSUE TITLE
Computer column is always second even if re-ordering

### ISSUE THREAD

**Issue by truekonrads** [Azure/Azure-Sentinel#1099]
**Describe the bug**
If there is a "Computer" column, it is always displayed second, regardless of any re-ordering (e.g. project-reorder)

**To Reproduce**

Run a query similar to this:
```
CommonSecurityLog
| where DeviceVendor == "Some Vendor"
| extend Computer=DestinationHostName
| project-reorder DeviceEventClassID,Activity,Computer,SimplifiedDeviceAction,FileName,
```
Observe that columns are: TimeGenerated, Computer and then others.

**Expected behavior**
Order follows project-reorder clause

**Screenshots**
![image](https://user-images.githubusercontent.com/1421150/93970531-de09cb80-fda0-11ea-86f5-3b8e0850b256.png)

**Desktop (please complete the following information):**
 - OS: Chrome on Windows 10

**Comment by shainw** [comment]
@truekonrads - thanks, we will have a look at it.

**Comment by shainw** [comment]
@truekonrads - through some testing, this appears to occur when Extend is used.  I am checking on it with the engineering team that owns it.  Thanks.

**Comment by shainw** [comment]
@truekonrads - thanks again for sharing.  This is by design for when expand is uses.  That said, the engineering team is looking at a design change to include fields that are generated thru expand to be part of the project-reorder operation.  I cannot give you a date at this time, but it is now in the list of future work items.

**Comment by shainw** [comment]
Closing, this was resolved a bit ago. :)
