### ISSUE TITLE
Bug in Version 1.2 of the Okta Data Connector

### ISSUE THREAD

**Issue by d-wat** [Azure/Azure-Sentinel#1122]
The latest update to the Okta Data Connector is failing:

ERROR: ConvertFrom-Json : Conversion from JSON failed with error: Unexpected character encountered while parsing value: @. Path '', line 0, position 0.

The error occurs on line 92 of the script:
 $responseObj = $response | ConvertFrom-Json

The previous version converted the response to JSON before sending it, but that line was removed.  The response is not in JSON format when it gets to the line  $responseObj = $response | ConvertFrom-Json

**Comment by monban** [comment]
I believe the issue was introduced in #936, the problematic area is [line 92 of run.ps1](https://github.com/chicduong/Azure-Sentinel/blob/c615e5781352f5e681709a2824b4eefbacead0f2/DataConnectors/Okta%20Single%20Sign-On/AzureFunctionOktaSSO/AzureFunctionOktaSSO/run.ps1#L92) in the Okta Connector. This line is attempting to convert the `$response` object from JSON, but the object returned by `Invoke-RestMethod` is already deserialized. This causes `ConvertFrom-Json` to throw an `ArgumentException`.

**Comment by preetikr** [comment]
Hi @monban - thanks, for reporting the issue. Can you please try out the fix in the commit mentioned above and see if this works for you? Please confirm as well. Thanks.

**Comment by monban** [comment]
@preetikr we've deployed the okta-response branch and it corrects the problem. Thank you!

**Comment by preetikr** [comment]
Nice - Thanks, @monban for validating this. I've approved and merged the PR, hence closing this issue.
