### ISSUE TITLE
Ubiquiti Solution Doesn't Use Custom Logs via AMA

### ISSUE THREAD

**Issue by doodlemania2** [Azure/Azure-Sentinel#11423]
**Describe the bug**
The solution says Custom Log via AMA is required, however, so I set that up. However, the solution itself still wants to use the now deprecated connector when running reports or queries.

**To Reproduce**
1. Install AMA, configure log ingestion from Unifi's SNMP trap on premise. Logs flowing into Sentinel's Log Analytics Ubiquiti_CL
2. Install solution
3. Do not configure the deprecated connector
4. No results are being found

**Expected behavior**
Results in Hunting, Logs, etc produce

**Comment by v-sudkharat** [comment]
Hi @doodlemania2, Thanks for flagging this issue, we will investigate this issue and get back to you with some updates. Thanks!

**Comment by v-sudkharat** [comment]
@doodlemania2, Could you please let us know which solution version you are using? 
And please also know what error you're facing while configuring the rule or running the Parser. Thanks!

**Comment by doodlemania2** [comment]
Hi there, here's the version info:
![Image](https://github.com/user-attachments/assets/c025deb2-50ff-4fad-826b-564e2b988d26)
which creates two connectors - the deprecated one and the AMA one:
![Image](https://github.com/user-attachments/assets/93af8fa3-a2bc-4989-abd9-48f39554f850)
I set up the AMA log and logs are flowing:
![Image](https://github.com/user-attachments/assets/f72f6be5-5cd6-466d-9052-139781a3dfd9)
but the workbooks and other components are (at least appear) to still be looking for data from the deprecated connector:
![Image](https://github.com/user-attachments/assets/91f54f34-ad94-4066-a177-05c28d2bb4a4) -- isn't configured because deprecated
![Image](https://github.com/user-attachments/assets/66539590-6bff-4bc1-a963-f9c57c004051)

**Comment by v-sudkharat** [comment]
@doodlemania2, Thanks for the sharing detailed info. we will check into the issue and get back to you. Thanks!

**Comment by v-sudkharat** [comment]
@doodlemania2, waiting for logs to investigate. Thanks!

**Comment by doodlemania2** [comment]
Sent you email offline

**Comment by v-sudkharat** [comment]
@doodlemania2, Received. 
You can send the **Ubiquiti_CL** in csv format by setting the last 24 hr durations.

**Comment by v-sudkharat** [comment]
@doodlemania2, Thanks!

**Comment by v-sudkharat** [comment]
@doodlemania2, After running the below parser is it give the result? -
![Image](https://github.com/user-attachments/assets/2dfcbfea-4f93-44ad-9ea2-a19ea93c03b1)

for us with your shared data it does not parse - 
![Image](https://github.com/user-attachments/assets/0934d922-5b2d-4ed1-a2e8-1b5f708f454d)

**Comment by v-sudkharat** [comment]
@doodlemania2, 
Actually, the solution contents (Connector,Workbook,rules) are Parser dependent, so the message which you received into the table - **Ubiquiti_CL** is not in an expected format. 
And due to that the contents are not showing any results.
We found the sample data in our repo in which the message format has been mentioned - 
`"Message": "<30>Mar  9 14:51:17 U7PG2,18e8296c3188,v10.10.10.1075: logread[1491]: Logread connected to 10.10.10.10:22022"`

https://raw.githubusercontent.com/Azure/Azure-Sentinel/refs/heads/master/Sample%20Data/Custom/UbiquitiAuditEvent.json

When we use the above data for testing, the solution content shows the results -
![Image](https://github.com/user-attachments/assets/6ed842c3-6515-4d2e-9f16-863ff2194243)

![Image](https://github.com/user-attachments/assets/e5b9ef0a-ddfb-44e5-9bb8-fbd530ea5e09)

So, could you please check in source itself and the source configuration to get correct format in message. Thanks!

**Comment by doodlemania2** [comment]
I'm afraid I don't know what you're asking.

I set up the custom log connector because the ubiquiti one is deprecated. Are you saying that I should be using the deprecated connector instead?

**Comment by v-sudkharat** [comment]
@doodlemania2, No, the configuration you did are correct one. No need to use the old, deprecated connector. 
So, the data received in a Message column is in a different format and due to that the workbook not showing any results, the expected message format should be like - 
`"Message": "<30>Mar  9 14:51:17 U7PG2,18e8296c3188,v10.10.10.1075: logread[1491]: Logread connected to 10.10.10.10:22022"`
This message format came from source itself, which is Ubiquiti side, so can you check is there any log format option are available? or which needs to be enabled, to get the correct message log. 

Thanks!

**Comment by doodlemania2** [comment]
Oh I see, thank you. I'm not given any options in Ubiquiti to configure:
![Image](https://github.com/user-attachments/assets/a8773f86-df40-4f7b-a649-f31016948a01)

and on the Azure side, not doing any transformations:
![Image](https://github.com/user-attachments/assets/75b2f67d-114d-4a21-96aa-30b8ad41bcd3)

output:
![Image](https://github.com/user-attachments/assets/2e6da051-a8fc-442d-a5cb-2b858e363abb)

**Comment by doodlemania2** [comment]
Oh, I think I see the problem. Do you have updated instructions for how to configure rsyslog such that the AMA agent picks up the correct datasouce?

**Comment by doodlemania2** [comment]
Okay, I think I have it working now - I am getting logs inside the parser:
![Image](https://github.com/user-attachments/assets/8337ed51-a3ee-4c28-b1fb-44e4c5bfd347)

Does this look right?

**Comment by v-sudkharat** [comment]
@doodlemania2, Great. 
Now you can check for the rest of the solution content, it should work as data has been parsed. 
Please let us know if any issues are there. Many thanks!

**Comment by v-sudkharat** [comment]
@doodlemania2, is there anything for us? if your issue has been resolved, can we close this from GitHub?

**Comment by doodlemania2** [comment]
Looks good - thank you for the great help!

**Comment by CYoung2024** [comment]
Good day @doodlemania2, 
Any chance you remember how you got the logs to the expected format? I have no configuration options in Ubiquiti either. Did you parse them somehow locally?

**Comment by doodlemania2** [comment]
I gave up trying :(
