### ISSUE TITLE
azuredeploy.json references a totally different story

### ISSUE THREAD

**Issue by Sebastian-Negoescu** [Azure/Azure-Sentinel#1217]
Hello,

Looking over the article that references this Playbook (https://techcommunity.microsoft.com/t5/azure-sentinel/playbooks-amp-watchlists-part-1-inform-the-subscription-owner/ba-p/1768917), I see that the code references a different Playbook (https://techcommunity.microsoft.com/t5/azure-sentinel/playbooks-amp-watchlists-part-2-automate-incident-response-for/ba-p/1771676).

What is the proper code repo for the first article? :) (Playbooks & Watchlists Part 1: Inform the subscription owner) - don't mean to offend, but the documentation is rather lacking info - doesn't feel friendly or complete at all... For instance, what is inside the "Filter array to get AzureResource identifier" from a Dynamic content point of view? How does the "first(...)" expression behave? What do we need to write there?

Cheers,
Sebi N.

**Comment by lior-tamir** [comment]
Julian, I sent a fix PR no. 1278

Sebi  I appreciate the feedback. 
Since you get the template ready for deploy and start use, I gave a short description on each step. Would you like to see more information on each step, although you are not requested to change it? Will be happy to make it more user friendly.

**Comment by sarah-yo** [comment]
Fix has been deployed
