### ISSUE TITLE
How to create the hunting and detection queries on the custom logs?

### ISSUE THREAD

**Issue by h19861104** [Azure/Azure-Sentinel#1579]
hi
I use the REST API to stream my system syslog data into the Azure Sentinel and i can see my syslog data in one SW_syslog_CL table.

I see the Hunting and detection queries are base on the CommonSecurityLog or SecurityEvents, but now i want to create the Hunting and detection queries on my syslog data SW_syslog_CL, how can i do that?

**Comment by chinguyen1** [comment]
@h19861104 You'd need to create Parsers to map the data from your custom log table to the CommonSecurityLog & SecurityEvents table. Then use the parsers in the hunting and detection queries, instead of these tables with pre-defined schema. 
This repo should give you some sample parsers: https://github.com/Azure/Azure-Sentinel/tree/master/Parsers

**Comment by chinguyen1** [comment]
@h19861104 If you have any other questions, please reach out. Otherwise, we'll close the issue.
