### ISSUE TITLE
Tools expecting OSSEM schema break due to case convention

### ISSUE THREAD

**Issue by lukiffer** [Azure/Azure-Sentinel#1709]
**Describe the bug**
_This is really more a request for clarification than an actual bug._

Parsers that are supposed to implement [OSSEM](https://github.com/OTRF/OSSEM-CDM/tree/master/schemas) schemas are pascal case (not snake case). 

**Additional context**
PRs like #1040 imply that they're implementing OSSEM but are in fact using pascal case variants of OSSEM entities and properties.

Is this intentional (i.e. Microsoft is adopting this variant of OSSEM as its officially supported schema, not OSSEM)?

**Comment by shainw** [comment]
@YaronFruchtmann  and @Cyb3rWard0g - Can you two respond to this feedback?

**Comment by YaronFruchtmann** [comment]
Thanks, lukiffer, for your interest and comments.
This is intentional to be consistent with all other LA tables.

**Comment by lukiffer** [comment]
Thanks @YaronFruchtmann for confirming. @Cyb3rWard0g is are the OSSEM schemas meant to be fluid in this way? Or would is this variant a different animal with which we should expect direct integration/compatibility with other OSSEM tools?

**Comment by Cyb3rWard0g** [comment]
Hello @lukiffer ! OSSEM schemas were initially created to follow "snake_case". Azure Sentinel is adopting OSSEM schemas, but Azure Sentinel is being consistent with "PascalCase" format already set for other LA tables as mentioned in the previous comment. OSSEM is meant to be "snake_case" by default. We are in conversations to potentially move to "PascalCase" or allow an easy translation with a simple bash or python script. I believe that since everything is YAML, it should be easy to do the conversion programmatically while using OSSEM as code.

**Comment by lukiffer** [comment]
@Cyb3rWard0g thanks for the insight. Are these conversations happening in the OSS space? If so could you provide a link?

It just occurred to me that the whole model could be abstracted behind a declarative projection mechanism, not just case. But that could defeat (at least part of) the purpose.

In any case, would love to contribute to the solution regardless of its implementation.
