### ISSUE TITLE
SecurityIncident creating duplicate Events

### ISSUE THREAD

**Issue by Lodewyk-Git** [Azure/Azure-Sentinel#2012]
**Describe the bug**
When you change the properties of an Incident an additional event is created in the SecurityIncident table. This makes it really hard to measure the amount of actual Incidents with the relevant comments and other data.

**To Reproduce**
1. Go to 'Incident'
2. Change Severity
3. Change Severity again
4. Change status
3. Search for Incident in Security Incident table

**Expected behavior**
No duplication or another way of measuring data from Log analytics.

**Screenshots**
![SecurityIncidents](https://user-images.githubusercontent.com/36856692/112311817-c7402500-8cae-11eb-8b53-d26115655bc3.jpg)

**Additional context**
I also can't measure via the SecurityAlert table as it's immutable. See #1911 
Which is why it's status is always new/dismissed.

**Comment by sarah-yo** [comment]
Hello @Lodewyk-Git, this is expected behaviour as tables in Log Analytics are immutable and cannot be changed after they have been ingested. Thus, when an incident is updated in the SecurityIncident table we have to write a fresh entry. 

There is way to remove duplicate entries from your queries by using the "arg_max" KQL operator on the TimeGenerated column:

SecurityIncident
| where CreatedTime >= ago(1h)
| summarize arg_max(TimeGenerated, *) by IncidentNumber

Here I am querying the SecurityIncident table for all the incidents raised in the past hour.

Hope this clarifies for you!

**Comment by Lodewyk-Git** [comment]
Thanks @sarah-yo 

Kinda sucks that it's like this, but if it can't be changed then so be it.
