### ISSUE TITLE
Close-Incident-ASCAlert

### ISSUE THREAD

**Issue by guidovbrakel** [Azure/Azure-Sentinel#2037]
Close-Incident-ASCAlert fails in the Get-Incident step with the following error:
{
  "statusCode": 404,
  "message": "Resource not found"
}

**Comment by swiftsolves-msft** [comment]
When the logic app is triggered it should send a payload of JSON with it including within the trigger body fields for
 
SystemAlertId,
WorkspaceSubscriptionId,
WorkspaceId,
WorkspaceResourceGroup
 
these fields values are passed into the second action to lookup the details of the incident so those values can be used to close the incident in sentinel in 3rd action. Within the second action those values above in trigger body appear to be missing to pass into 2nd action where we get the 404 because the lookup path should look something like this in the Show RAW Input on 2nd action
 
    "path": "/Cases/774324c5-8868-6429-8cca-db843679a8e8/SUBID/WORKSPACEID/rgswiftoperations",
 
"path": "/Cases/SYSTEMALERTID/SUBID/WORKSPACEID/WORKSPACERESOURCEGROUPNAME",
 
 
In testing I was triggering the Logic App manually through Azure Sentinel Incident > View Full Details > view playbooks > Close-Incident-ASCAlert > Run.

![image](https://user-images.githubusercontent.com/30509195/113215829-764da500-9249-11eb-936b-c2b5c8cdf0f2.png)
![image](https://user-images.githubusercontent.com/30509195/113215845-7f3e7680-9249-11eb-971c-14075a1bab7c.png)
![image](https://user-images.githubusercontent.com/30509195/113215870-85345780-9249-11eb-94e9-6c1ca88b7fa9.png)

**Comment by guidovbrakel** [comment]
I'm now getting this error:
 "code": "AuthorizationFailed",
            "message": "The client '*' with object id '*' does not have authorization to perform action 'Microsoft.Security/locations/alerts/dismiss/action' over scope '/subscriptions/ab1a262a-4cb0-440d-a7ca-07858c64a0cd/resourceGroups/Sample-RG/providers/Microsoft.Security/locations/centralus/alerts/2517850392292469503_89d0f5aa-97ad-45c7-b35f-bf45d5f749f4' or the scope is invalid. If access was recently granted, please refresh your credentials."

**Comment by swiftsolves-msft** [comment]
This action uses HTTP action to POST with the Logic App MSI, you can check to make sure the Logic App as an identity has proper access (SecurityAdmin at Sub level) to dismiss the ASC Alert.

![image](https://user-images.githubusercontent.com/30509195/113312787-a2fccd80-92d8-11eb-97e5-31974770811a.png)

![image](https://user-images.githubusercontent.com/30509195/113312882-b60f9d80-92d8-11eb-8dba-9a5b648dbf49.png)

Another thing to check is that the message of _'/subscriptions/id/resourceGroups/Sample-RG/providers/Microsoft.Security/locations/centralus/alerts/2id'_

Is the URI being created correct does the id \ \ \ \ \ line up ?

![image](https://user-images.githubusercontent.com/30509195/113314361-3e427280-92da-11eb-9ca3-cb249eb85a50.png)

**Comment by guidovbrakel** [comment]
Why at sub level? There is not security administration role at sub level right?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by swiftsolves-msft** [comment]
The original purpose is for the SOC engineer to close the Sentinel Incident with playbook which will then dismiss the duplicate ASC Alert. You could edit/modify the Logic App actions and delete the action that closes the Sentinel Incident, the rest of the chain should work, KQL query and dismissal of ASC Alert.

Also check out the following Logic App from last year it acts as a background sync engine so when Sentinel Incident is Closed it dismisses any corresponding ASC Alerts. > [https://github.com/swiftsolves-msft/Azure-Sentinel-Playbooks/tree/master/IncidentClosed-Sync-ASCAlertDismiss](https://github.com/swiftsolves-msft/Azure-Sentinel-Playbooks/tree/master/IncidentClosed-Sync-ASCAlertDismiss) It acts as a one way close sync though.

**Comment by guidovbrakel** [comment]
Thanks @swiftsolves-msft
