### ISSUE TITLE
OKTA connector stop running after setup

### ISSUE THREAD

**Issue by a-kefallonitis** [Azure/Azure-Sentinel#2077]
OKTA official connector stop running after the initial setup and ingesting logs

Anyone seen this before ? Any steps to troubleshoot further ?

**Comment by sreedharande** [comment]
@a-kefallonitis Can you please raise an ICM ticket.
https://aka.ms/icm

**Comment by v-jayakal** [comment]
@a-kefallonitis - An Incident https://portal.microsofticm.com/imp/v3/incidents/details/237443706/home has been created for this issue. An email has sent to Alex kefallonitis with next steps to be done - update of the function deployed and requested to provide the invocation details. A Powershell Script has also been provided for verification. Since ICM is created, closing this  issue.
