### ISSUE TITLE
Solution ARM file contains non-unique default value

### ISSUE THREAD

**Issue by tj-senserva** [Azure/Azure-Sentinel#2088]
**Describe the bug**
The Solution mainTemplate ARM file contains a non-unique default value for the LA Workspace name

**To Reproduce**
1. Submit Solution for template generation
2. Use generated template to submit offer to Marketplace

**Expected behavior**
The generated template would pass Marketplace offer validations 

**Additional context**
https://solutiontemplates.visualstudio.com/marketplacesolutions/_git/senservallc/pullrequest/10744

I see the same value for the Infoblox template

**Comment by tj-senserva** [comment]
Tagging @v-maudan

**Comment by elforb** [comment]
Hello,

The link provided in the Additional Context section is not accessible for me. Could you provide more detail on the particular value you are seeing? Especially since you're seeing it in multiple solutions.

I've compared both SenservaPro and Infoblox solutions, and both workspace parameter default values contain the expected value: `<Enter Log Analytics Workspace>`
The LA Workspace name is a parameter to the template, so it must be selected by the user in the Create UI.

**Comment by v-jayakal** [comment]
@tj-senserva, Can you please provide us more details.

**Comment by tj-senserva** [comment]
Hello @elforb,

The reviewer from the Marketplace team noted that the Log Analytics Workspace needed to be a unique name.

![MarketplaceReviewError](https://user-images.githubusercontent.com/59487793/115928982-9f2e1800-a44c-11eb-9446-4c574b0255e6.PNG)

I think some discussions took place between the Sentinel and Marketplace teams that I was not a part of, as the Solution has been accepted now. I believe the issue can be closed

**Comment by v-jayakal** [comment]
Based on the response from @tj-senserva , closing this issue. Thanks.
