### ISSUE TITLE
ThreatIntelligence duplicate data

### ISSUE THREAD

**Issue by maced12** [Azure/Azure-Sentinel#2112]
**Describe the bug**
I am ingesting TI to Azure Sentinel and every time I try to update an existing IOC it generates an additional record with modified fields and also shows old records when querying. For example, I created an IOC with a confidence score of 90 and ingested it, later I updated the confidence score to 80 and reingested it. When querying it will show both IOCs with confidence scores of 90 and 80 rather than deleting the old one. Old records show up until the retention period.

Tried all TI data connector, Graph API, and TI preview tab, get duplicates regardless of the source.

**To Reproduce**
1. Add IOC in Azure Sentinel via data connector, Graph API, or TI preview tab.
2. Update IOC and re-ingest.
3. Query the IOC and it will show both old and updated IOC.

**Expected behavior**
After updating the old IOC, there should only be the updated IOC and single entry.

**Additional context**
I understand it might take some time for updated IOCs to show up but in this case, old entries stay until they are deleted due to the retention policy. I know the issue can be resolved when querying by using arg_max( ) but is this expected behavior?

**Comment by jwes2** [comment]
@maced12 the ThreatIntelligenceIndicator table in Logs is write-only. So modified indicators will always result in a new row being added to the table. This is expected behavior. All of the analytics rule templates supplied out of the box related to matching threat intelligence with other table data account for this by including syntax (the arg_max function you mentioned) to only use the latest copy of an indicator when performing matching.

**Comment by shainw** [comment]
Closing as answered.
