### ISSUE TITLE
Move-LogAnalytics-to-Storage: Cannot write more bytes to the buffer than the configured maximum buffer size: 104857600

### ISSUE THREAD

**Issue by aleixsb** [Azure/Azure-Sentinel#2268]
**Describe the bug**
When trying to move some tables to a Storage Account with the provided playbook it fails to do so if the table is bigger than the  buffer size.

**To Reproduce**
Configure the playbook from the provided template and run it against some big tables.

**Expected behavior**
Create a hourly log file in the storage account
**Screenshots**
![image](https://user-images.githubusercontent.com/5330902/117638805-85e2d680-b183-11eb-9216-a2035d4e2bb8.png)

**Additional context**
Probably the problem can be solved by modifing the query timeframe for those big tables.

**Comment by SivPothana** [comment]
You are getting this error because you are using Logic App managed identity to call the Azure Sentinel API.
But it looks like the identity has not been granted appropriate access to Azure Sentinel linked Log analytics workspace.

I have gone through the guide(Automating Azure Sentinel: Using Playbooks to extract data - Bridewell Consulting) you shared with me for 
this playbook and it mentions the below in its prerequisites.

“You will then need to Assign RBAC ‘Log Analytic Reader’ role to the Logic App at the required level.”

So. Please follow the below steps to grant RBAC for the Logic App identity.
•Under Access control  in you Log analytics workspace, select Add role assignment.

Please refer below documentation for additional information.
https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal

**Comment by SivPothana** [comment]
Hello Aleix,

The azure log analytics call was failing due to response being greater than 100 MB Data.

At the below approach to export data from your log analytics workspace to storage account.

Please review the below link it will usefully.
https://docs.microsoft.com/en-us/azure/azure-monitor/logs/logs-data-export?tabs=portal&WT.mc_id=Portal-Microsoft_Azure_Support

**Comment by aleixsb** [comment]
Hey @SivPothana ,

Thanks for sharing but in most cases it won't be useful as it doesn't work for custom tables.

**Comment by sreedharande** [comment]
@aleixsb - The legacy custom log won’t be supported in export. The next generation of custom log available in preview early 2022 can be exported
https://docs.microsoft.com/en-us/azure/azure-monitor/logs/logs-data-export?tabs=portal#limitations

If you want to export Custom logs to storage, please try the following PS Utility
https://github.com/sreedharande/MoveLogs2StorageAccount
