### ISSUE TITLE
error downloading the template 

### ISSUE THREAD

**Issue by DeanGross** [Azure/Azure-Sentinel#2275]
**Describe the bug**
There was an error downloading the template from URI 'https://raw.githubusercontent.com/Azure/Azure-Sentinel/master/Playbooks/Get-SOCActions/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below. 

**To Reproduce**
1. Go to https://github.com/rinure-msft/Azure-Sentinel/tree/master/Playbooks/Get-SOCActions
2. click deploy to azure

**Expected behavior**
the template gets added

**Comment by Lodewyk-Git** [comment]
Hi, this is a version created by Rinure-msft, I can see that there isn't a deployment file yet, unfortunately you'll have to wait until it's created and pushed to master or alternatively follow this guide: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/quickstart-create-templates-use-the-portal#edit-and-deploy-the-template

and paste the contents from https://github.com/rinure-msft/Azure-Sentinel/blob/master/Playbooks/Get-SOCActions/Get-SOCActions.json by step 4 instead of making the changes

**Comment by sreedharande** [comment]
@DeanGross - Thanks, This issue has been fixed. Please let us know, if you see any other issues
