### ISSUE TITLE
G-suite connector documentation does not match reference docs

### ISSUE THREAD

**Issue by artro03** [Azure/Azure-Sentinel#2278]
**Describe the bug**
In this article, it talks about consuming a token.pickle file.  However, in the Google reference doc, it creates a token.json file.  

**To Reproduce**
Compare the google doc referenced - https://developers.google.com/admin-sdk/reports/v1/quickstart/python
and this doc.  The Google doc creates a .json file while we consume a .pickle file.  The process and file formats need to align for this to work.

**Expected behavior**
Both docs need to create a .pickle or a .json file.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-jayakal** [comment]
@artro03 - can you give the google doc you are referring? Thanks.

**Comment by artro03** [comment]
Hello
I put this in the original ticket as the Google reference doc - Python
Quickstart  |  Reports API  |  Google Developers
<https://developers.google.com/admin-sdk/reports/v1/quickstart/python>

**Comment by marb08** [comment]
@artro03 I found a temporary workaround until both the documentations will be aligned.

As you receive a _.json_ file, it is necessary to modify both the script for the string generation and the _\_\_init\_\_.py_ file that will match those changes inside the Azure Function App on Azure.
These changes  force to run the Option 2 in the deployment section inside the Connector page (_Option 2 - Manual Deployment of Azure Functions_) and deploy manually the app on cloud.

You can find the new changes in the following repo:
- new script for _.json_ auth file: [here](https://github.com/marb08/Azure-Sentinel/blob/master/DataConnectors/GoogleWorkspaceReports/get_json_string.py)
- new _\_\_init\_\_.py_ file that reads encoded json string: [here](https://github.com/marb08/Azure-Sentinel/blob/master/DataConnectors/GoogleWorkspaceReports/GWorkspaceReportsAPISentinelConnector/__init__.py)

Hope that helps.
Let me know if there are any suggestions or issues related.

**Comment by v-jayakal** [comment]
@artro03 , can you please the update for the instruction steps and let us know if these steps help you to get the pickle string (using step 2(Generate_Google_Pickle_String.py)
PR link here: https://github.com/Azure/Azure-Sentinel/pull/2397
Please let us know, Thanks.

**Comment by marb08** [comment]
@v-jayakal line 27 of _Generate_Google_Pickle_String.py_ the port has to be integer value, not str:

So instead of: `creds = flow.run_local_server(port='8081')`
the line has to be: `creds = flow.run_local_server(port=8081)`

Moreover, the python script to convert the pickle string at the [link ](https://github.com/Azure/Azure-Sentinel/blob/GworkspaceReportsConnector/DataConnectors/GoogleWorkspaceReports/get_pickle_string.py)that you posted is getting 404.

**Comment by ZsoltPath** [comment]
@v-jayakal as far as I see the Google isn't providing pickle string any more. 
We need to handle a JSON credentials file like @marb08 

The correct link is: https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/GoogleWorkspaceReports/get_pickle_string.py

**Comment by marb08** [comment]
> @v-jayakal as far as I see the Google isn't providing pickle string any more.
> We need to handle a JSON credentials file like @marb08
> 
> The correct link is: https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/GoogleWorkspaceReports/get_pickle_string.py

I agree with you @ZsoltPath, but for what concern the pickle string, I think that @v-jayakal and his team, in order to avoid to rewrite the entire documentation, prefer to add a little workaround to convert the actual output form Google credentials (json) to the one written inside the MS docs (pickle).
Thank you for the link, I was just informing @v-jayakal that the link in the Pull request [(link)](https://github.com/Azure/Azure-Sentinel/pull/2397) was getting a 404.

**Comment by ZsoltPath** [comment]
>... I think that @v-jayakal and his team, in order to avoid to rewrite the entire documentation, prefer to add a little workaround to convert the actual output form Google credentials (json) to the one written inside the MS docs (pickle) and then from there follow the steps reported in the documentation with the pickle string.

I'd rather not comment that. :(

**Comment by TaEduard** [comment]
Hey guys, 

I did test the solution from @v-jayakal but i keep getting:

2021-06-24T23:10:00Z   [Error]   Error while loading pickle string: invalid load key, 'n'.

I highly doubt i am copy pasting the pickle string wrongly ...

**Comment by v-maudan** [comment]
@TaEduard , just copy paste the pickle string from single quotes.[PFB screenshot for ref]

![image](https://user-images.githubusercontent.com/75478517/123369732-eeeba580-d59b-11eb-87c6-ad33c42c3a99.png)

**Comment by guarismo** [comment]
I also reported this a while ago.
[https://github.com/MicrosoftDocs/azure-docs/issues/73553](url)

My workaround was to go back in Google's repo and pulled the script that generates a pickle instead of the json.

[ https://github.com/googleworkspace/python-samples/raw/aacc00657392a7119808b989167130b664be5c27/admin_sdk/reports/quickstart.py](url)

**Comment by v-maudan** [comment]
@artro03 , can you please check updated instruction steps and let us know if these steps help you to get the google pickle string .
PR link here: [#2397](https://github.com/Azure/Azure-Sentinel/pull/2397)

**Comment by v-maudan** [comment]
@artro03, Can you please check updated instructions. ?  [#2397](https://github.com/Azure/Azure-Sentinel/pull/2397) Thanks!

**Comment by artro03** [comment]
Hello
I work for Microsoft and opened this for a client.  They have
successfully enabled the connector prior to this update via a support
ticket.  I will ask them to check again, but I don't have a G-suite to
validate it.

**Comment by v-maudan** [comment]
Thanks @artro03, Can you please ask them to check and let us know if it resolve the issue. We will merge this [PR #2397](https://github.com/Azure/Azure-Sentinel/pull/2397).

**Comment by v-jayakal** [comment]
This change has been implemented, hence closing this.
