### ISSUE TITLE
Fortigate Playbook Deployment Error

### ISSUE THREAD

**Issue by YoshiakiOi** [Azure/Azure-Sentinel#2280]
**Describe the bug**
Got an error shown on the screenshot when I tried to deploy the playbooks of Fortigate.

**To Reproduce**
1. Go to https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Fortinet-FortiGate
2. Click on Deploy to Azure

**Screenshots**
![image](https://user-images.githubusercontent.com/33479286/117908659-c5d8c380-b313-11eb-9ee8-553d8b5ba73d.png)

**Desktop (please complete the following information):**
Browser: Edge

**Comment by Lodewyk-Git** [comment]
Hi @YoshiakiOi,

Try the deployment for every individual Playbook:

https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Fortinet-FortiGate/Playbooks/Fortinet_IncidentEnrichment
https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Fortinet-FortiGate/Playbooks/Fortinet_ResponseOnIP
https://github.com/Azure/Azure-Sentinel/tree/master/Playbooks/Fortinet-/Playbooks/Fortinet_ResponseOnURL

I believe this error was caused the most recent update. (3 Playbooks instead of 1)

You'll see that the path to the old deployment does not exist.

**Comment by v-jayakal** [comment]
@YoshiakiOi , a PR https://github.com/Azure/Azure-Sentinel/pull/2363 has been raised with fix for this issue.

**Comment by preetikr** [comment]
@YoshiakiOi - Let us know if the PR mentioned works for you. 
@v-jayakal - Let's update the Fortigate solution with the fix.

Thanks!
