### ISSUE TITLE
Auto Disabled Analytic Rule

### ISSUE THREAD

**Issue by Ziy-sws** [Azure/Azure-Sentinel#2392]
Hi Guys 

Has anyone notice that some rules are showing up as Auto disabled for some reason?

![Screenshot 2021-06-03 125246](https://user-images.githubusercontent.com/52692970/120633608-a04e5e00-c46a-11eb-84c2-bb7a0236a152.jpg)

**Comment by sarah-yo** [comment]
Hi @Ziy-sws 

This is expected behaviour when analytics rules are consistently failing. Please check the logic of your rules that have been auto disabled because something in there must be making the rule fail (logic wrong, referring to tables/workspaces that don't exist, etc.)

More details can be found here - https://docs.microsoft.com/en-us/azure/sentinel/tutorial-detect-threats-custom#issue-a-scheduled-rule-failed-to-execute-or-appears-with-auto-disabled-added-to-the-name

Thanks!
