### ISSUE TITLE
Move-LogAnalytics-to-storage playbook fails for SecurityEvent data type

### ISSUE THREAD

**Issue by Ashish-Hingmire** [Azure/Azure-Sentinel#2477]
Hello ,
I am trying to implement this playbook for my environment where the requirement is to keep the data in archival for more than 3 yrs. While running this playbook, It failed for Security event data type as the file size of an hour was growing larger then 100MB.
Is there a way we can change the size limit to higher value? If yes, how? If not then can we change the function to pull the data on hourly or 30 mins basis? 
I assume this issue will be applicable to bigger environments where the incoming events are on higher side.

Awaiting your quick response.

**Comment by malowe101** [comment]
Hi @Ashish-Hingmire,

You are correct in that larger orgs or data sets will have an issue with being moved. Currently there are hard API limitations that the Logic App runs into that we cannot change (from the Azure Sentinel team side). Our workarounds are the following:

- change the time interval for the query to be every 10-30 minutes depending on table size . You would change the hours count variable to be minutescount, change the addhours to addminutes within the time range expression and set it to 30 (or your time interval of choice) instead of 1. Lastly, update the increment variable action to add 30 minutes to minutescount instead of 1. formatDateTime(addMinutes(variables('StartDate'),add(int(variables('MinutesCount')),30)))

- set up dedicated versions of this Logic App that only move your large data sources (securityevents, syslog, etc). This will allow you to filter deeper into those logs to break up the amount of data that is being moved within each block.

- set up continuous export of logs to storage accounts. This will allow you to move data as soon as it is ingested and you will avoid the issues that you are running into with the Logic App: https://docs.microsoft.com/en-us/azure/azure-monitor/logs/logs-data-export?tabs=portal
