### ISSUE TITLE
DeploymentFailed The API 'IP-API' could not be found.

### ISSUE THREAD

**Issue by dbwav** [Azure/Azure-Sentinel#2700]
DeploymentFailed
The API 'IP-API' could not be found.

How to fix and where to deploy?

**Comment by sarah-yo** [comment]
Hi @dbwav 

Could you provide some more details about the issue you're experiencing please, per the bug report template.

Thanks.

_**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here._

**Comment by dicolanl** [comment]
#2696 should fix this.

**Comment by dbwav** [comment]
Still not fixed. 
![deploy-fail1](https://user-images.githubusercontent.com/87608612/126331637-8086e30b-b2a8-46d1-ac8c-94b404f644bc.JPG)

**Comment by dicolanl** [comment]
Try now found a typo
[A screenshot of a computer  Description automatically generated with medium confidence]

From: dbwav ***@***.***>
Date: Tuesday, July 20, 2021 at 6:24 AM
To: Azure/Azure-Sentinel ***@***.***>
Cc: Nicholas DiCola (SECURITY JEDI) ***@***.***>, Comment ***@***.***>
Subject: Re: [Azure/Azure-Sentinel] DeploymentFailed The API 'IP-API' could not be found. (#2700)

Still not fixed.
[deploy-fail1]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F87608612%2F126331637-8086e30b-b2a8-46d1-ac8c-94b404f644bc.JPG&data=04%7C01%7CNicholas.DiCola%40microsoft.com%7C85d231a7c21b47807c6e08d94b81a4c5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637623842459393780%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2KVSi1YwLlNCXsm3ESc5V5Y7EQQ6nuivvCBVgGK2DCQ%3D&reserved=0>

**Comment by dbwav** [comment]
Still getting same error. 

{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "ApiNotFound",
      "message": "The API 'IP-API' could not be found."
    }
  ]
}

**Comment by dbwav** [comment]
I am using the 'Deploy with alert trigger' deployment link

**Comment by dicolanl** [comment]
Ok i just tested too.  1st deploymment failed.  hit deploy again and it works. just noticed the template is missing a dependsOn.

________________________________

**Comment by dbwav** [comment]
Deployment succeeded. 
Thank you!

**Comment by dbwav** [comment]
So as a followup - after deployment tried to run playbook against an incident. 
Got the following error. I redacted clientRequestId for purpose of this example.
Both subscription id and resource group are valid. Not sure about JSON part as I made no changes to deployment.

{
  "error": {
    "code": 400,
    "source": "logic-apis-westus2.azure-apim.net",
    "clientRequestId": "redacted",
    "message": "The response is not in a JSON format.",
    "innerError": "Invalid subscription id or resource group"
  }
}
