### ISSUE TITLE
Hunting issues for GithubAudit for repo.destroy isn't working

### ISSUE THREAD

**Issue by majorvin** [Azure/Azure-Sentinel#3038]
**Describe the bug**
Trying to hunt using the prebuilt one but getting error GitHub Mass Deletion of repos or projects

**To Reproduce**
Prebuild query is
```
let starttime = todatetime('2021-09-14T18:36:03.836Z');
let endtime = todatetime('2021-09-15T18:36:03.836Z');
let LearningPeriod = 7d;
let EndLearningTime = starttime - LearningPeriod;
let NumberOfStds = 3;
let MinThreshold = 10.0;
let GitHubRepositoryDestroyEvents = (GitHubAudit
    | where Action == "repo.destroy");
GitHubRepositoryDestroyEvents
| where TimeGenerated between (EndLearningTime .. starttime)
| summarize count() by bin(TimeGenerated, BinTime)
| summarize AvgInLearning = avg(count_), StdInLearning = stdev(count_)
| extend LearningThreshold = max_of(AvgInLearning + StdInLearning * NumberOfStds, MinThreshold)
| extend Dummy = 1
| join kind=innerunique (
    GitHubRepositoryDestroyEvents
    | where TimeGenerated between (starttime .. endtime)
    | summarize CountInRunTime = count() by bin(TimeGenerated, BinTime)
    | extend Dummy = 1
    )
    on Dummy
| project-away Dummy
| where CountInRunTime > LearningThreshold
```

ERROR MESSAGE: 
'summarize' operator: Failed to resolve scalar expression named 'BinTime'

**Comment by shainw** [comment]
@majorvin - We are currently in process of migrating to GitHub queries to the new preview connector - 
![image](https://user-images.githubusercontent.com/45466083/149210535-e75173f6-6c45-4c6e-8d9a-0ec468c4d691.png)

While that is in process, after onboarding the GitHub data via the existing custom connector the data is loaded into a table called GitHub_CL.  In order to use the data more easily, there is a parser that must be installed in your workspace - https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/GitHub/GitHubAuditLog.txt.  This includes the following instructions - 

// Usage Instruction : 
// Paste below query in log analytics, click on Save button and select as Function from drop down by specifying function name and alias. 
// To work with pre-built GitHub queries this Function should be given the alias of GitHubAudit.
// Functions usually takes 10-15 minutes to activate. You can then use function alias from any other queries (e.g. GitHubAudit | take 10).

If you have done this and still having issues, can you share an output from this command - `GitHub_CL | getschema`

**Comment by majorvin** [comment]
HI @shainw  is this in public preview? I dont see it in the list of connectors.

<img width="504" alt="Screen Shot 2022-01-12 at 3 34 50 PM" src="https://user-images.githubusercontent.com/1380446/149217471-8de7ffef-0ba9-4fa7-be0b-429e2fbe79e2.png">

**Comment by shainw** [comment]
@majorvin - Apologies for the long delay on this.  In early February we released this content that will help you enable GitHub monitoring - https://techcommunity.microsoft.com/t5/microsoft-sentinel-blog/microsoft-sentinel-continuous-threat-monitoring-for-github/ba-p/3037154.
