### ISSUE TITLE
Disabled Account Detection won't fire

### ISSUE THREAD

**Issue by aew-takeahike** [Azure/Azure-Sentinel#306]
**Describe the bug**
For this detection: https://github.com/Azure/Azure-Sentinel/blob/master/Detections/SigninLogs/DisabledAccountSigninsAcrossManyApplications.yaml

I think line 31 should be
      | where count_ >= threshold

**Screenshots**
No results:
![image](https://user-images.githubusercontent.com/54727064/64376511-156ad600-cfee-11e9-9c0c-f38840f34879.png)

Success with modified code:
![image](https://user-images.githubusercontent.com/54727064/64376339-a55c5000-cfed-11e9-8a38-9dcb22f55e36.png)

**Comment by shainw** [comment]
@aew-takeahike - Thanks for the feedback.  We have set the threshold related to the number of distinct applications where the disabled account attempted to sign into.  Because this is an Alert, we don't want to fire unless we have a higher confidence level.  You are welcome to modify the alert with your own parameters, I would suggest modifying the let statement for the threshold to something lower.  If you set it to 1, then you would also receive the alert.  We will keep an eye on the feedback for this one and can certainly change the default threshold if that is what is desired by the community.  Thanks, Shain
