### ISSUE TITLE
Nsg Resource_id display

### ISSUE THREAD

**Issue by nichap** [Azure/Azure-Sentinel#351]
**Describe the bug**
Hi i want to make one of my query result the Resource Id to automate the lonk to my   Network Security Group resource. I have this output "/subscriptions/<MY-SUBSCRIPTION-ID>/ressourceGroups/<MY-RG>/providers/Microsoft.Network/networkSecurityGroups/<MY-NSG-NAME>", that is the resource id definition of NSG. But it's not detected as resource id and it's not automatically create the link to the ressource. I have define properly the column settings but nothing change.

Br,

Nicolas

**Screenshots**
The column Settings
![Capture d’écran 2019-10-18 à 13 59 00](https://user-images.githubusercontent.com/46745641/67092610-fa27e480-f1af-11e9-82e5-3434601b7a33.png)

My query Result
![Capture d’écran 2019-10-18 à 13 59 26](https://user-images.githubusercontent.com/46745641/67092634-0ad85a80-f1b0-11e9-9795-f42154e71a03.png)

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [Mozilla]
 - Version [ 69.0.3]

**Comment by shainw** [comment]
Apologies for the delay.  This issue is not specifically related to Threat Hunting in Azure Sentinel and I am not exactly sure what the issue could be.  Please open a support ticket so we can troubleshoot this with you - https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request
