### ISSUE TITLE
OMSAgent - CEF connector - security_events.conf regex doesn't take into account %ASA-session- format

### ISSUE THREAD

**Issue by guarismo** [Azure/Azure-Sentinel#3779]
Messages formatted %ASA-session-<Severity>-<Evetnt ID> are rejected by the OMSAgent

**To Reproduce**
1. Install and configured the CEF connector as documented
2. Send a sample: 

logger -p local4.warn -d -n 127.0.0.1 -P 514 "Dec 15 2021 09:34:34 EDT: %ASA-session-5-106100: access-list acl_in permitted tcp inside/10.1.2.16(2241) -> outside/192.0.0.89(2000) hit-cnt 1 first hit [0x71a87d94, 0x0]"

3. Look at the OMSAgent logs into /var/log/microsoft/omsagent/log/omsagent.log for warnings of message rejected

**Expected behavior**
See logs in Sentinel in the CommonSecurityLog table

**Screenshots**
![ASA-session-number-eventid](https://user-images.githubusercontent.com/33353023/147146602-5324585c-59e3-454e-a20d-6ec547e15f5f.png)

**Additional context**
Trying to change the regex in the security_events.conf permits the logs to get in Sentinel but not properly parsed:

![image](https://user-images.githubusercontent.com/33353023/147147632-379cdac3-3c0b-4a09-8c01-828db7bcb4c7.png)

**Comment by v-jayakal** [comment]
Consulted @NoamLandress as he is SME for CEF issues and here is the response: 
We don’t support this format. As the customer mentioned- in one of the agent configuration files there is a regex picking up the Cisco ASA events starting with this format:
%ASA[0-9\-]{8,10})
The events the customer is sending start with %ASA-session, which are invalid.
The customer edited this regex in the configuration file to pick up his events, which works, but the specific field he is referring to is populated in the workflow during ingestions, using a dictionary of values based on the OriginalLogSeverity value, as seen here:
 
Since the customers OriginalLogSeverity value is not one of those in the dictionary, the LogSeverity field value remains empty.

Please let us know if anything else is needed.
Thanks.

**Comment by guarismo** [comment]
Can we please have this format supported in Sentinel? 
Please consider this an Enhancement Request.

**Comment by sarah-yo** [comment]
@guarismo please raise this as a feature request here, thanks! 

https://feedback.azure.com/d365community/forum/37638d17-0625-ec11-b6e6-000d3a4f07b8
