### ISSUE TITLE
Sentinel Repositories deployment does not work with remote workspace analytic rules

### ISSUE THREAD

**Issue by d0p4m1n31** [Azure/Azure-Sentinel#3937]
I hope that someone has a fix for this, since I am not able to deploy analytic rules with a remote workspace (workspace('name').table in it. For the main workspace, it works without any issues. I can create the rules manually to the remote workspace without any issues.

The error states "Status Message: Make sure you have the necessary permissions on all the workspaces in your query, specifically on 'DemoSentinel'. (Code: Unauthorized)". Anyone knows how to fix this?

**Comment by nayef-yassin** [comment]
@d0p4m1n31 Is the remote workspace in the same resource group as the workspace with the connection? 

The service principal created with the connection creation only has permissions within the resource group - it can manually be configured to have broader permissions, have you tried that approach?

**Comment by Ge3kySaint29** [comment]
I am seeing the same error message as above. 

To answer the following question:
Is the remote workspace in the same resource group as the workspace with the connection?
No – the remote Sentinel workspace resides in another tenant outside of our managing tenant. Due to Azure architecture, we are seeing limitations for leveraging the service principal across multiple tenants.
 
What we are trying to achieve – is develop analytic rules leveraging Lighthouse queries as we want to added correlated data from multiple (customer) tenants into a single query for our managing tenant. Our CICD fails due to the service principal being unable to access the additional Sentinel instances outside of the managing tenant. 

Is there a way to allow service principals to go across tenant boundaries to enable CICD rule deployments for Sentinel?

**Comment by nayef-yassin** [comment]
@Ge3kySaint29 The deployment app is deployed on a Resource Group level with no access to anything outside of that RG by design (for security purposes). The deployment app is granted Sentinel Contributor role within the resource group and you can manually change that using IAM in your resource group. Are you able to grant it a higher or custom role that allows for it to access external resources? It seems far fetched especially with Lighthouse but worth a try. 

I will note down your need to check internally if there are ways to enable this scenario.

**Comment by Ge3kySaint29** [comment]
> Are you able to grant it a higher or custom role that allows for it to access external resources?
Based on the documentation, this is only for additional management groups (PREVIEW), subscriptions, and other resources within the **same** tenant. This would need to cross over tenant boundaries in order for successful CICD deployment, due to it need the proper permissions to see the additional workspaces. I can manually add these queries with the workspaces included with no issues, but the automation piece fails even though it has the Sentinel Contributor role same as myself.

https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles

**Comment by bartlomiej-czyz** [comment]
Is there any update on this issue?
Making the Sentinel deployment app multi-tenant and granting it Microsoft Sentinel Contributor role in the other tenant doesn't help.

**Comment by nayef-yassin** [comment]
@bartlomiej-czyz we don't currently have an update on this. I've filed this as a backlog item for the team. Since service principals are confined to a single tenant by default we need to try and unblock this multi-tenant querying scenario without compromising the default setup of the deployment SP. I will provide an update if the team is able to provide a workaround. Thanks again for raising this.

**Comment by Ge3kySaint29** [comment]
> @bartlomiej-czyz we don't currently have an update on this. I've filed this as a backlog item for the team. Since service principals are confined to a single tenant by default we need to try and unblock this multi-tenant querying scenario without compromising the default setup of the deployment SP. I will provide an update if the team is able to provide a workaround. Thanks again for raising this.

Please include myself with the respecting correspondence. Thanks.

**Comment by rafalkitab** [comment]
Is there an update/fix on that one? This is the exact same issue we are facing.

**Comment by nayef-yassin** [comment]
@rafalkitab No update at the moment. This will require redesign so it is expected to take some time. 

Just to clarify, are you also looking to deploy content from one connection across multiple tenants or deploy in a single tenant while querying external tenants?

**Comment by rafalkitab** [comment]
Yes, this is exactly what I'm looking to do.

**Comment by Jeremyp87** [comment]
This should be a pretty basic feature and was under the impression it would be able to do this. I'll revert back to PowerShell deployment for now.

**Comment by jakristensen** [comment]
> @rafalkitab No update at the moment. This will require redesign so it is expected to take some time.
> 
> Just to clarify, are you also looking to deploy content from one connection across multiple tenants or deploy in a single tenant while querying external tenants?

I am also trying to achieve this

**Comment by mwittersict** [comment]
Facing the same issue. The CICD tries to create queries that use an external workspace, But the Service Principal has no access to this workspace. (and will never get access because of security reasons).
Is there perhaps an option to disable this check?

**Comment by ryangthompson** [comment]
By deploying a **disabled** cross-workspace analytic rule, the CICD validation check is bypassed and GitHub actions deploys it without error.  However, when I tried modifying the rule and setting enable to true the CICD the deployment fails as rule validation is ran.  There is definitely a need for this capability so hopefully a fix or loop hole is created soon.

**Comment by BALROG3** [comment]
+1, same issue. MDRs and MSSPs commonly deploy content to large numbers of Resource Groups. Organisations such as ours are also most in need of the automation offered by DevOps/Github integration. This is a significant gap. Please prioritise...

**Comment by Mahoneyman** [comment]
Hello is there any update on this. 

Jan 2024 and I am having this issue so I think it may still be broken.

**Comment by hchiphong** [comment]
+1, same issue

**Comment by bacatta** [comment]
can you re-open this issue please ?

**Comment by bacatta** [comment]
For my usecase, I workaround this with those commands:
```
az role assignment list --role "Microsoft Sentinel Contributor" --scope "/subscriptions/xxx/resourceGroups/source" | jq .[].principalId
"zzz"

az role assignment create --assignee-object-id "zzz" --role "Microsoft Sentinel Contributor" --scope "/subscriptions/xxx/resourceGroups/target" --assignee-principal-type ServicePrincipal
```

**Comment by smant-chorus** [comment]
For now we used an existing service principal connected to the other tenants via lighthouse to send the content, this helped avoid permission issues with cross workspace queries. Same identity used to push content in before using repositories. Not sure if this will help anyone else. I wish Microsoft would let us MSPs enter in our own service principal instead of auto creating a new one within the target tenant. 

You can create a new secret in GitHub with this template and refer to that new secret in the deploy yml file.

Secret format:
```
{
  "clientId": "",
  "clientSecret": "",
  "tenantId": "YourHomeTenantID",
  "subscriptionId": "TargetCustomerSubId",
  "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
  "resourceManagerEndpointUrl": "https://management.azure.com",
  "activeDirectoryServiceEndpointResourceId": "https://graph.windows.net",
  "graphEndpointUrl": "https://graph.windows.net"
}
```
Example deploy yml snip:
```
    steps:
    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' }}
      with:
        creds: ${{ secrets.YOURCUSTOMSPSECRET }}
        enable-AzPSSession: true
```
