### ISSUE TITLE
"Anomalous sign-in location by user account and authenticating application" query not displaying locationString in results.

### ISSUE THREAD

**Issue by jasong-cyqual** [Azure/Azure-Sentinel#4147]
**Describe the bug**
Regarding "AnomalousUserAppSigninLocationIncrease-detection.yaml", the project operator (| project TimeGenerated, AppDisplayName , UserPrincipalName, locationString ) does not project locationString anywhere in the query results.

**To Reproduce**
1. Run the default query on the "Anomalous sign-in location by user account and authenticating application" rule.

**Expected behavior**
locationString (trcat(tostring(LocationDetails.countryOrRegion), "/", tostring(LocationDetails.state), "/", tostring(LocationDetails.city), ";")) should be projected somewhere in the query results. However, it does not.

**Comment by tatecksi** [comment]
Hi @jasong-cyqual  
After the 'project' command, the query creates a time series to calculate the number of distinct locations by UserPrincipalName and AppDisplayName with the following line:

"| make-series dLocationCount = dcount(locationString) on TimeGenerated in range"

Hence, you will find dLocationCount column instead of locationString.
