### ISSUE TITLE
QualysKB connector doesn't return any results

### ISSUE THREAD

**Issue by infernuxmonster** [Azure/Azure-Sentinel#4239]
**Describe the bug**
We've set up both the QualysVM and QualysKB data connectors for our Sentinel env.
The VM connector works fine, but it does not include CVEs so it isn't suited for reporting or easily mapped to other tools. 

This is where the QualysKB connector comes in. It's deployed and works like the QualysVM. 
Result of this is our connector has been running for 5 months now and the table (currently) is empty. Nothing has been changed from default settings on the current implementation.

**To Reproduce**
1. Go to Microsoft Sentinel and find Qualys KB in Data Connectors 
2. Click on Deploy to Azure
3. Fill in relevant information (API User, PW and URI)
4. Let the function app run (without errors)

**Expected behavior**
QualysKB_CL table is filled with all known vulnerabilities from the KB.

**Additional context**
Not sure the implementation of QualysKB is the best it can be. Maybe just a big pull monthly and then daily runs to look for updates. Currently the connector holds little value as it does not provide the ability to map historic vulnerabilities from QID to CVEs.

**Comment by v-rucdu** [comment]
@infernuxmonster :Thanks for helping us testing the fix. We have merged the fix for this to master (https://github.com/Azure/Azure-Sentinel/pull/4433). 
Please revert the package to point to the master branch (https://aka.ms/sentinel-qualyskb-azuredeploy) 
Please feel free to reopen in case you face any issues... Thanks!!
