### ISSUE TITLE
Enrich-Incident-Alienvault-OTX Playbook

### ISSUE THREAD

**Issue by kraken8585** [Azure/Azure-Sentinel#4418]
Hi,

How can we ensure that this playbook does not perform an external OTX lookup for internal IPs and internal domains?

**Comment by teachjing** [comment]
There are two options and both options will require a watchlist
https://docs.microsoft.com/en-us/azure/sentinel/watchlists

- You can add an additional action in the playbook that filters that list of Internal IPs and internal domains prior to the lookup action.

- But even better, you should do a lookup against a watchlist in your query. That way you can filter those IPs and domains so only the interesting entities not on the watchlist are included to be checked against OTX.

**Comment by farces** [comment]
I know this is ancient, but we bumped into this as well (as OTX responds with a 400 Bad Request if a private IP is submitted and this breaks out of the for loop without checking the rest of the IP entities on the Incident), our fix was to add a condition in the For each IP loop that checks that "IPs Address" is not private before making the API call, and moving the branch under that condition:

![Image](https://github.com/user-attachments/assets/d1e0a555-eea7-47d5-94ea-a2330784fb8f)

![Image](https://github.com/user-attachments/assets/38fb77ba-0f78-4bad-9e20-eb650bc60d81)

Since any private IP submitted to OTX is a fatal error I don't see any reason to use a watchlist with specific in-use private IP ranges, and as such this condition can and probably should be included in the Playbook by default.

We don't use this Playbook for URL lookups so I haven't adapted any logic to avoid submitting internal URLs on that branch, and I'm not sure if OTX responds with 400 Bad Request on that branch either. I imagine it's better to use a watchlist as mentioned above for that case, unless you're keen to maintain a list of TLDs and check against that (masochism required).
