### ISSUE TITLE
Antivirus scan result output-Azure Sentinel logic-apps

### ISSUE THREAD

**Issue by chenhaobb2** [Azure/Azure-Sentinel#4626]
Issue description:
I can't see the Antivirus scan result.
The connector action is supposed to be completed with the status "Pending".

How can I see the Antivirus scan result.Please lend force.
e.g. 
Full scan is complete.... there is a threat.
or
As a result of scanning, which file is detected where
Quarantined.

Image of issue:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/71550574/163082366-d7dcf473-7de2-4733-8e8b-7b239259d2a9.png">

**Comment by BenjiSec** [comment]
hi @chenhaobb2, it's Pending because we send request to run AV via API. To get status later, you can use "Actions - Get list of machine actions" or if you have action ID to use "Actions - Get single machine action". But you will need to add some delay so that AV can run. 
![Screenshot 2022-05-03 144534](https://user-images.githubusercontent.com/61513156/166464739-420cd1d4-100a-45a7-8245-7b764158d323.png)
