### ISSUE TITLE
'summarize' operator: Failed to resolve scalar expression named 'TimeGenerated'

### ISSUE THREAD

**Issue by Akshay250692** [Azure/Azure-Sentinel#4808]
Hi Everyone,

I am struggling to define time within query for workbook. My kql is represent 10 deny action followed by 1 allow connection with same external source IP to private destination IP with in 300 second. First deny connection should be Start time and first allow connection should be end time. Source IP should be summarize so we can check how many external source ip successed to make connection with in 24 hours or 48 hours. Please some one help me to get proper result for workbook.

let threshold=10;
let threshold1=1;
let authenticationWindow = 5m;
let a=
CommonSecurityLog
| where DeviceVendor == "Palo Alto Networks" and DeviceProduct =~ "PAN-OS"
| where DeviceAction == "deny"
| where (ipv4_is_private(SourceIP) == 'False' and ipv4_is_private(DestinationIP) == 'True')
| summarize denycount = count() by DeviceAction, SourceIP, DestinationIP
| where denycount >= ["threshold"];
let b=
CommonSecurityLog
| where DeviceVendor == "Palo Alto Networks" and DeviceProduct =~ "PAN-OS"
| where DeviceAction == "allow"
| where (ipv4_is_private(SourceIP) == 'False' and ipv4_is_private(DestinationIP) == 'True')
| summarize allowcount = count() by DeviceAction, SourceIP, DestinationIP
| where allowcount >= ["threshold1"];
a|join kind = inner(b) on SourceIP
| summarize StartTimeUtc = min(TimeGenerated), EndTimeUtc = max(TimeGenerated) by bin(TimeGenerated, authenticationWindow), SourceIP, DestinationIP, denycount, allowcount

**Comment by tatecksi** [comment]
Hi @Akshay250692,

You can give the following sample query a try:

let threshold=10;
let threshold1=1;
let authenticationWindow = 5m;
CommonSecurityLog
| where DeviceVendor == "Palo Alto Networks" and DeviceProduct =~ "PAN-OS"
| where (ipv4_is_private(SourceIP) == 'False' and ipv4_is_private(DestinationIP) == 'True')
| where DeviceAction in ("deny","allow")
| summarize StartTime = minif(TimeGenerated,DeviceAction=="deny"), EndTime = minif(TimeGenerated,DeviceAction=="allow"),make_list(DeviceAction), DestinationIP = make_set(DestinationIP), denyCount=countif(DeviceAction=="deny"),allowCount=countif(DeviceAction=="allow")
by bin(TimeGenerated,authenticationWindow),SourceIP
| where denyCount>=threshold and allowCount >=threshold1
| where list_DeviceAction[10] == "allow"



By the way, since this is not an 'issue', the [Microsoft Tech Community Discussion](https://techcommunity.microsoft.com/t5/microsoft-sentinel/bd-p/MicrosoftSentinel) would be the right place to raise your question.
