### ISSUE TITLE
Combining two related incidents into one

### ISSUE THREAD

**Issue by moh10ly** [Azure/Azure-Sentinel#518]
We are trying to combine a correlated incidents from different connectors (WDATP And Azure ATP) into one incident with an interval of lets say 30 mins. 

Is it possible to do so and what would be the criteria to get such related incidents? 

Thank you

**Comment by oshezaf** [comment]
Hi @moh10ly : I believe you refer to alerts, as those connectors send alerts rather than incidents (which is what a rule would create after correlation). You can correlated alerts using a rule as alerts are just another type of event stored in the SecurityAlert table. As to how to write a correlation rule, you can refer to our writing rules webinar: [YouTube](https://youtu.be/pJjljBT4ipQ), [Deck](https://1drv.ms/b/s!AnEPjr8tHcNmghhrDiXV1NeTZCZI)
