### ISSUE TITLE
Google IAM Function app executes successfully but no events are ingested

### ISSUE THREAD

**Issue by miraclesoul** [Azure/Azure-Sentinel#5392]
**Describe the bug**
Google IAM function app is executing successfully but no events are ingested from GCP.

**Expected behavior**
Events/logs should be ingested in sentinel after successful execution of the function app.

**Screenshots**
Attached
<img width="938" alt="success without events" src="https://user-images.githubusercontent.com/15667254/174673491-7fe3a5a3-b006-4f6e-a5f9-734754d0b8cb.png">

**Comment by sysadmin256** [comment]
I'm seeing this too, looks like it was due to commit #5856 where the files were moved by @q-andrikoshundi 

The fix for me was to go into the function app and update the WEBSITE_RUN_FROM_PACKAGE Application Setting from 
https://github.com/Azure/Azure-Sentinel/blob/master/DataConnectors/GoogleWorkspaceReports/GWorkspaceReportsAPISentinelConn.zip?raw=true 
to 
https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/GoogleWorkspaceReports/Data%20Connectors/GWorkspaceReportsAPISentinelConn.zip?raw=true

I had deployed the Google connector from the Sentinel Marketplace.  Moving the zip file above seems to have broken the function app since it was pointing to an invalid URL.  What's the best way to avoid this in the future?  Should I copy the zip and deploy from my own environment?

**Comment by v-amolpatil** [comment]
Hi @miraclesoul, thank you for flagging this. Apologies for the delayed response. If you still need assistance, please reply here within 5 business days.

**Comment by v-amolpatil** [comment]
Hi @miraclesoul, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond within next 2 days. If we don't receive response by 8 Feb 2023, we will close this issue.

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #5392 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
