### ISSUE TITLE
URGENT HELP: Failure Exception: ModuleNotFoundError: No module named 'requests' error 

### ISSUE THREAD

**Issue by alakijaD** [Azure/Azure-Sentinel#5485]
**Describe the bug**
I have had cisco umbrella configured for 9 months without issues. Since the 23rd June 2022 the logs are not feeding into Sentinel due to a:

"Failure
Exception: ModuleNotFoundError: No module named 'requests'"

I have done everything between making a custom template to support Python runtime 3.8 instead of Python 3.6 to editing init.py to install requests before "import requests" . All to no avail. We are unable to do much more and need urgent help with this for our SOC.

**To Reproduce**
1. On azure portal open function apps
2. Click on your cisco umbrella function app
3. View transaction searches over the last 30 minutes 
4. See error: Exception while executing function: Functions.ciscoUmbrellaDataConn Result: Failure
Exception: ModuleNotFoundError: No module named 'requests'. Troubleshooting Guide: https://aka.ms/functions-modulenotfound
Stack:   File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 315, in _handle__function_load_request
    func = loader.load_function(
  File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 42, in call
    raise extend_exception_message(e, message)
  File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 40, in call
    return func(*args, **kwargs)
  File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/loader.py", line 85, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/site/wwwroot/ciscoUmbrellaDataConn/__init__.py", line 1, in <module>
    import requests

**Expected behavior**
Usually the compiler recognises the requests library and is able to make http requests to- the AWS S3 bucket and pull logs to our sentinel account accordingly.

**Comment by alakijaD** [comment]
Relieved that it's not an issue just on our side! 
Was pulling my hair out, as I had tried:
 - reconfiguring the code in the WEBSITE_RUN_FROM_PACKAGE to install requests module before import.
 - updating the python compiler within sentinel
 - creating new function apps 
 All failed
 our AWS team also confirmed nothing changed as far as their access policy allowing sentinel to access the S3 bucket.
 
 Hope the MSFT team are able to resolve soon :)

**Comment by piercosta** [comment]
Hi,
we are experiencing the same behaviour in two different Azure Function in production since 23rd of June.
We have already engaged Azure Support.

Exception while executing function: Functions.ciscoUmbrellaDataConn Result: Failure
Exception: ModuleNotFoundError: No module named 'requests'. Troubleshooting Guide: https://aka.ms/functions-modulenotfound
Stack:   File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 314, in _handle__function_load_request
    func = loader.load_function(
  File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 42, in call
    raise extend_exception_message(e, message)
  File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/utils/wrappers.py", line 40, in call
    return func(*args, **kwargs)
  File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/loader.py", line 85, in load_function
    mod = importlib.import_module(fullmodname)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/site/wwwroot/ciscoUmbrellaDataConn/__init__.py", line 1, in <module>
    import requests

**Comment by alakijaD** [comment]
Yeah thought as much!

Thanks @piercosta, we will have to do the same for the time being.

Old zip works like a charm cheers

**Comment by craiginfotech** [comment]
This reversion technique is not working for me. I accidently discovered we weren't getting logs since the 23rd while investigating the runtime v4 announcement and how to mitigate. I've attempted to work with Cisco and Microsoft and they are currently pointing fingers at each other on this issue. Who is responsible for maintaining and supporting this Data Connector?

**Comment by craiginfotech** [comment]
Heh. Just took a minute to get data again. The reversion actually does work. Still doesn't answer the question though of who might be responsible for supporting this data connector? Is it Cisco or Microsoft? Who would I speak to regarding the runtime v4 announcement to vet whether this will continue to be supported when runtime v3/v2 is retired?

**Comment by sreedharande** [comment]
Thanks @thinkdreams

**Comment by thinkdreams** [comment]
@sreedharande why was this closed? this is only a temporary fix to the solution, not the whole solution. Whatever was committed last week in 5180 broke the functionality, and what was provided here was just a workaround. Someone needs to correct this - as in December, Microsoft is going to require v4 of the runtime, meaning that this may not work again if this issue is not resolved.

**Comment by thinkdreams** [comment]
> Hi, we fount the issue with some help from Azure Support. Commit [0d8dd59](https://github.com/Azure/Azure-Sentinel/commit/0d8dd59617811fe4dd44d18dc4f4b7bf1952a432) May 31, 2022 broke something. The file CiscoUmbrellaConn.zip is smaller and there are a bunch of missing libraries.
> 
> Every time the function app restarts it gets an updated CiscoUmbrellaConn.zip. To fix temorarly you can use an older CiscoUmbrellaConn.zip, for example https://github.com/Azure/Azure-Sentinel/blob/0f534907ce1f19b6d22f77b75b5b4b4763b92d9e/DataConnectors/CiscoUmbrella/CiscoUmbrellaConn.zip?raw=true
> 
> To revert to that version you should change the config WEBSITE_RUN_FROM_PACKAGE to reference https://github.com/Azure/Azure-Sentinel/blob/0f534907ce1f19b6d22f77b75b5b4b4763b92d9e/DataConnectors/CiscoUmbrella/CiscoUmbrellaConn.zip?raw=true and restart the function app.

@sreedharande - See the above quote.

**Comment by piercosta** [comment]
> @sreedharande why was this closed? this is only a temporary fix to the solution, not the whole solution. Whatever was committed last week in 5180 broke the functionality, and what was provided here was just a workaround. Someone needs to correct this - as in December, Microsoft is going to require v4 of the runtime, meaning that this may not work again if this issue is not resolved.

Microsoft has updated the connector. The new version should be fixed by now, so using the latest version is the permanent solution. Regarding your question about runtime v4, Microsoft is both the developer of the Cisco Umbrella connector and the provider of Azure Functions, so i am hopeful that they will fix it by then :)

**Comment by thinkdreams** [comment]
@piercosta thanks for the patience and response! i'll revert to using the original code then so it pulls the latest Data Connector zip and test. I really appreciate the support. Never know who to go to on these because the Provider is marked Cisco - and we're Umbrella support customers, so I had to go through the wringer with Cisco TAC before Umbrella support pointed me back to Microsoft. MS support wasn't much help - but I'm super glad there's a nifty community here.

That said, I'm learning Sentinel as I go, and I guess I'll need to learn more about GitHub, so I apologize if I seem like a NOOB on GitHub - because, well, I am :)

**Comment by thinkdreams** [comment]
@sreedharande , @piercosta updated me on the situation.

**Comment by philtapp** [comment]
I've moved back, pointing to the master branch rather than a specific (older) commit URL, and the newly posted version there appears to be working correctly so far - it's certainly not throwing exceptions on every execution about missing dependencies anymore and event data is flowing into Sentinel.
