### ISSUE TITLE
DataSource.Error: OData:  'microsoft.windowsDefenderATP.api.Software'.

### ISSUE THREAD

**Issue by DanielaSilvaMS** [Azure/Azure-Sentinel#5996]
https://github.com/Azure/Azure-Sentinel/tree/master/Tools/M365-PowerBi%20Dashboard

Error: DataSource.Error: OData: The property 'category' does not exist on type 'microsoft.windowsDefenderATP.api.Software'. Make sure to only use property names that are defined by the type or mark the type as open type.
Details:
    DataSourceKind=OData
    DataSourcePath=https://api.security.microsoft.com/api/Software

When refresh: 
let
    ODataSource = customODataQuery("Software","table"),
    Column1 = ODataSource{0}[Column1],
    #"Added Custom" = Table.AddColumn(Column1, "Non Exposed devices", each [installedMachines]-[exposedMachines]),
    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Non Exposed devices", Int64.Type}})
in
    #"Changed Type"

**Expected behavior**
Is expected to work (some weeks ago was working)

**Desktop July 2022 (2.107.683.0)

**Comment by v-rbajaj** [comment]
Hi @DanielaSilvaMS, the provided link isn't working. 
Although there is something you can try based on the error message you provided, it seems that the Power BI dashboard is trying to access a property called 'category' on the 'microsoft.windowsDefenderATP.api.Software' type, but this property does not exist. This error could occur due to changes in the API that the dashboard is using.
To resolve this issue, you could try updating the Power BI dashboard to use the correct property name or to reflect any changes in the API.
Another potential solution would be to mark the 'microsoft.windowsDefenderATP.api.Software' type as an open type, which would allow additional properties to be added dynamically. This could be done by modifying the code that defines the type, or by using an OData metadata document to specify that the type should be treated as an open type.

Once the issue has been resolved, you can refresh the dashboard to ensure that the data is updated correctly.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/3789 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
