### ISSUE TITLE
Cannot Deploy AzurePortalSigninfromanotherAzureTenant.yaml - Persistent storage path does not exist.

### ISSUE THREAD

**Issue by rweirtbg** [Azure/Azure-Sentinel#6195]
**Describe the bug**
When Attempting to deploy the AzurePortalSigninfromanotherAzureTenant.yaml analytic rule, we get the following error: `Persistent storage path 'https://download.microsoft.com/download/7/1/D/71D86715-5596-4529-9B13-DA13A5DE5B63/ServiceTags_Public_20220321.json' does not exist."`

https://github.com/Azure/Azure-Sentinel/blob/59739d2401edbca1e06c1abafd635640edaedc9b/Solutions/Azure%20Active%20Directory/Analytic%20Rules/AzurePortalSigninfromanotherAzureTenant.yaml

**To Reproduce**
1. Go to Analytic Rule Templates
2. Attempt to Create a Rule from Template for 'Azure Portal Signin from another Azure Tenant'
3. Step through to 'Rule Logic'

**Expected behavior**
No Error

**Screenshots**

<img width="1194" alt="Screen Shot 2022-09-21 at 2 36 13 AM" src="https://user-images.githubusercontent.com/111534841/191431692-e465a9e9-50b7-41bb-b0ed-98cd612cad9d.png">

**Comment by raldponsua** [comment]
Please use the latest or just renamed it to ServiceTags_Public_20220926 from ServiceTags_Public_20220321.json

**Comment by rweirtbg** [comment]
I tried creating it from the template again but the latest still links to ServiceTags_Public_20220321.json.

**Comment by tatecksi** [comment]
Hi @rweirtbg, as mentioned in the query's comment the url will be updated regularly so you would need to update the file name manually.

In order to fix it, edit the rule and replace "ServiceTags_Public_20220321.json" with **ServiceTags_Public_20221010.json**

![image](https://user-images.githubusercontent.com/25794051/195490267-45096783-126a-4f26-a7d7-aeb02e06b653.png)
