### ISSUE TITLE
[SailPoint IdentityNow] Unable to get the generate redirect URL for new API client to create credential

### ISSUE THREAD

**Issue by williamtwar** [Azure/Azure-Sentinel#6287]
**Describe the bug**
Unable to get the generate redirect URL for new API client to create credential

**To Reproduce**
1. Redirect URL requires me to input
![image](https://user-images.githubusercontent.com/90981031/193515133-7ddfcd5d-8fc5-4ea5-b67b-28b0d6bdff59.png)
2. I went to this page (see the screenshot), but I got 5 error logos after trying to save the custom connector.
![image](https://user-images.githubusercontent.com/90981031/193515428-4dc10b33-1c88-438b-9137-95b14ff6cb9f.png)

Would you mind advising on how to resolve this issue?

**Comment by dneto82** [comment]
Hi @williamtwar . I had success deploying the new content solution from scratch. 

Seems now you don't need that callback anymore, the triggered function now is doing all GET events from their API. Following instructions from the content catalog, I'm using PAT (Personal Access Token) instead of the API Management client secret from the previous solution.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/6287 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
