### ISSUE TITLE
Zoom - Sentinel Parsing error for Shared key in received events

### ISSUE THREAD

**Issue by deepanshumarwah** [Azure/Azure-Sentinel#635]
Zoom -Azure sentinel webhook integration has a parsing bug for shared key for line 82 in run.ps1
 $keyBytes = [Convert]::FromBase64String($SharedKey)

**To Reproduce**
1. Create azure function as mentioned in github repo using Arm template and integrate using zoom webhook as mentioned.
2. Go to azure function in portal and use log console for monitoring the function and start your zoom meeting. As you run a meeting or perform some activity on your zoom app. Azure function will be triggered. However the event received by Azure function will show this error in logs console.
please refer to error :
```
2020-04-30T13:25:20.607 [Error] ERROR: Exception calling "FromBase64String" with "1" argument(s): "The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters."
At D:\home\site\wwwroot\ZoomLogs\run.ps1:82 char:13
             $keyBytes = [Convert]::FromBase64String($SharedKey)
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
 FullyQualifiedErrorId : FormatException
Script stack trace:
   at Build-signature, D:\home\site\wwwroot\ZoomLogs\run.ps1: line 82
   at Post-LogAnalyticsData, D:\home\site\wwwroot\ZoomLogs\run.ps1: line 97
   at Write-OMSLogfile, D:\home\site\wwwroot\ZoomLogs\run.ps1: line 133
   at <ScriptBlock>, D:\home\site\wwwroot\ZoomLogs\run.ps1: line 145

System.Management.Automation.MethodInvocationException: Exception calling "FromBase64String" with "1" argument(s): "The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters."
   at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Management.Automation.Interpreter.DynamicInstruction 3.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
```

Expected Behavior: successful parsing of shared key for multiple expected formats.

**Comment by petebryan** [comment]
Hi @deepanshumarwah the $SharedKey variable that is passed to the Write-OMSLogfile function is your Azure Sentinel Workspace Key, which should be a Base64 encoded string. This is likely failing because the Workspace Key being passed to it is incorrect.

So a couple of things to check - first that the Workspace Key that you stored in KeyVault is correct (it should be a Base64 string). Secondly check that the workspaceKey parameter in your Function App is correctly referencing the KeyVault secret and has the authorization to access the secret. If you have correctly configured the KeyVault and parameter the Source column for that parameter should include a green tick icon and read "Key vault Reference":
![image](https://user-images.githubusercontent.com/8940401/80749597-8611b600-8adb-11ea-8942-fae18332dfbb.png)

If you continue to have issues with this you can [debug this function app locally](https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-local) and reference the Workspace Key directly to ensure that it is correct.
