### ISSUE TITLE
A

### ISSUE THREAD

**Issue by Teamnorthamerica** [Azure/Azure-Sentinel#6396]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by v-laanjana** [comment]
[[Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. iOS]
Browser [e.g. chrome, safari]
Version [e.g. 22]
Smartphone (please complete the following information):](https://github.com/Azure/Azure-Sentinel/issues/6778)](https://github.com/Azure/Azure-Sentinel/issues/6778)

**Comment by v-laanjana** [comment]
Description is missing for issue. Please raise new issue with description.
