### ISSUE TITLE
GoogleWorkspaceReports Solution

### ISSUE THREAD

**Issue by thatlazyadmin** [Azure/Azure-Sentinel#6772]
The function that gets deployed with the solution provides the following error.

First Error: When create Analytical Rules, the creation of the rules fails with **"union: must have at least one operand that can be evaluated successfully when running with 'Fuzzy' mode."** 

Second Error: Running a query in Log Analytics which references the Alias for the function. "
union: must have at least one operand that can be evaluated successfully when running with 'Fuzzy' mode.
If the issue persists, please open a support ticket. Request id: 7f2b319c-bdf5-4823-9138-c8e2db0ab009 "

Third Error: This is generated Azure Function Monitor Logs " 2022-11-30T12:30:00Z   [Error]   Executed 'Functions.GWorkspaceReportsAPISentinelConnector' (Failed, Id=7f5f74a1-81a4-4650-a737-33cef49f634a, Duration=300ms)"

How can this be resolve ?

**Comment by ashishsyal** [comment]
We are looking into this.

**Comment by v-amolpatil** [comment]
Could you please share the logs generated inside of azure function monitor logs so that we can investigate the issue. Refer below image and click on the date time for the failed record. In below image which is just for your reference, you will see at your end Failure instead of Success. Just click on datetime and send us all the logs in it.

![image](https://user-images.githubusercontent.com/107389644/207297870-92133e5b-2b3b-4a98-802a-376bb532a07f.png)

**Comment by v-amolpatil** [comment]
Since we have not received a response in the last 5 days, we are closing your issue #6772 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
