### ISSUE TITLE
NRT rule triggers 50 incidents

### ISSUE THREAD

**Issue by hazcod** [Azure/Azure-Sentinel#7062]
**Describe the bug**

We are currently using the native `NRT MFA Rejected by User` analytics rule, which should only trigger on the last minute.
However last night someone denied a MFA request, but this rule kept triggering every 5 minutes.

I'm not sure where else to report since we only have Basic support which does not include Sentinel..

**To Reproduce**
1. Setup `NRT MFA Rejected by User` AAD analytics rule in Sentinel.
2. Have someone deny a MFA prompt
3. See 50 incidents popup

**Expected behavior**

Only the two, same events in all incidents:

![image](https://user-images.githubusercontent.com/5222512/211258818-0cbda968-ff68-4113-bde2-a5dfc6832e1c.png)

![image](https://user-images.githubusercontent.com/5222512/211258854-078f4b36-9879-4fd3-b8dd-0dd9964363d5.png)

**Screenshots**

**Comment by hazcod** [comment]
It seems to be relevant to our Sentinel tenant, happening for other rules too.

**Comment by sammant** [comment]
My team are experiencing the same thing, also found this community post where I left a comment. This seems to impact all NRT rules since last week and in our case it's causing them to fire on the same logs every minute https://techcommunity.microsoft.com/t5/microsoft-sentinel/duplicate-incidents-created-by-nrt-rule/m-p/3711737.

This is the result after changing the incident grouping to 12 hours, forcing alerts to correlate into one incident for now. Note the timeframe vs created time, this is because the logs are the same.  
![sam_mnt_0-1673435426006](https://user-images.githubusercontent.com/15093312/211814390-8d2dbb00-e2d4-42fe-be69-2035beeaee61.png)

**Comment by hazcod** [comment]
@sammant Do you per chance have a commercial support license to create a case?

**Comment by sammant** [comment]
@hazcod We did plan to make a case but it seems to have stopped for us now, are you still seeing it your side?

**Comment by hazcod** [comment]
It seems Microsoft pushed a hotfix for it; https://techcommunity.microsoft.com/t5/microsoft-sentinel/duplicate-incidents-created-by-nrt-rule/m-p/3715495/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufExDVUxROFZSRzVKRkNMfDM3MTU0OTV8U1VCU0NSSVBUSU9OU3xoSw#M10493
