### ISSUE TITLE
Analytic Rule Template "Excessive number of failed connections from a single source (ASIM Network Session schema)" does not show proper results.

### ISSUE THREAD

**Issue by rweirtbg** [Azure/Azure-Sentinel#7304]
**Describe the bug**

Analytic Rule Template "Excessive number of failed connections from a single source (ASIM Network Session schema)" does not show proper results.

https://github.com/Azure/Azure-Sentinel/blob/master/Detections/ASimNetworkSession/ExcessiveHTTPFailuresFromSource.yaml

**To Reproduce**

In line 48 of the query, it appears that this attempts to filter _Im_NetworkSession results with EventResults that are failures.

  _Im_NetworkSession(eventresult='Failure')
  
This does filter out results that are not EventResult='Failure'. We see lots of EventReults='Success' events as well.

**Expected behavior**

Consider using the following instead:

_Im_NetworkSession
| where EventResult == "Failure"

This does properly filter the results.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by oshezaf** [comment]
Thanks @rweirtbg for raising the issue!

Since _Im_NetworkSession unifies a large number of different parsers, the issue is, most probably within one (or few) of the parsers. Therefore, to identify the issue, it would be very helpful if you identified the source or sources that are not filtered correctly. The following query can help:

_Im_NetworkSession (starttime=ago(1h), eventresult='Failure') | summarize by EventProduct, EventVendor, Type, EventResult

If you rather not identify the sources on the public GitHub, feel free to reach out tot me at ofer.shezaf@microsoft.com with the answers.

As to your suggestion: the use of filtering parameters instead of a where stattetment  is crucial to ensure performance rules.

**Comment by oshezaf** [comment]
@rweirtbg : an update - we have identified an issue with a recent parsers update which affect 6 built-in and solution rule templates, including this one. We are working to deploy a hotfix.

Meanwhile, you will have to edit the rules to avoid FPs here. The best way to do it, without reducing detection capabilities is:
- [Deploy](https://github.com/Azure/Azure-Sentinel/tree/master/Parsers/ASimNetworkSession) the patches version of the parser as a workspace function. 
- Replace _Im_NetworkSession with imNetworkSession in each rule.

**Comment by oshezaf** [comment]
@rweirtbg : the issue has now been resolved. There is no need for the workaround.

**Comment by rweirtbg** [comment]
Hi @oshezaf 

Thank you for looking into this. We ran some additional search tests and saw that the behavior is still occurring.

Screenshot:
<img width="1573" alt="Screenshot 2023-02-17 at 3 28 02 AM" src="https://user-images.githubusercontent.com/111534841/219593694-2045d6cd-e206-4aa5-a55e-b877fe7ddacd.png">

**Comment by oshezaf** [comment]
Hi @rweirtbg :

Based on the screenshot, your issue is indeed unrelated. Based on the DvcOriginalAction field I believe I identify the source and therefore the parser to check. This is not the parser we identified and corrected last week. The parser was for Windows security events firewall events (515x), which seems not to be your issue.

As I continue to investigate based on my guess, it would be better if in parallel you open a support ticket that will enable the support team to gather all needed information to make sure we instigate the right issue.

~ Ofer

**Comment by oshezaf** [comment]
Hi @rweirtbg : I have fixed an issue with the Fortinet parser. It may be your issue, but I do recommend openning a support ticket and providing the information they will ask to verify that it is not a different issue. 

The fix is currently available only in the GitHub version. To use the patches version at this time you need to [Deploy](https://github.com/Azure/Azure-Sentinel/tree/master/Parsers/ASimNetworkSession) the patches version of the parser as a workspace function and override the built-in parsers following the instructions [here](https://learn.microsoft.com/en-us/azure/sentinel/normalization-manage-parsers#use-a-modified-version-of-a-built-in-parser). It will be deployed to all workspaces as built-in parsers in the near future.

**Comment by oshezaf** [comment]
Hi @rweirtbg : the fix should be deployed to all workspaces.
