### ISSUE TITLE
Schema missing from URL field

### ISSUE THREAD

**Issue by cgiampoulakis** [Azure/Azure-Sentinel#7525]
https://github.com/Azure/Azure-Sentinel/blob/156b3e8bb2abdcc554f0cf7df205c93aa3e8fb8f/Parsers/ASimWebSession/Parsers/vimWebSessionPaloAltoCEF.yaml#L217

Hi,
According to HTTP session fields specification the schema (http, https, ...) is mandatory but seems to be not logged on Palo Alto logs.
That's an issue that can be resolved on the ASIM parser level?

What I am trying to do is use the parse_url function to break down the URL to path, query, ... but the function does not work without the schema.

Thanks,
Christos.

**Comment by oshezaf** [comment]
Hi @cgiampoulakis : the documentation is not consistent on this issue: if you go through the web session schema doc, you will find that there are opportunities in which you will not get a schema, and the schema is therefore not mandatory.  The reason is that in many cases it is not provided, and not even deducible from other fields, apart from guessing based on the port number. We therefore decided not to make it mandatory. I will update the docs accordingly.
