### ISSUE TITLE
JSONDecodeError when parsing Cloudflare logs

### ISSUE THREAD

**Issue by beachfires** [Azure/Azure-Sentinel#7576]
https://github.com/Azure/Azure-Sentinel/blob/e076a957cdda7af8365d7b8d22f8b0b7c0b2255d/Solutions/Cloudflare/Data%20Connectors/AzureFunctionCloudflare/main.py#L114

It seems like some characters that have made it in our Cloudflare logs have managed to halt the Cloudflare data connector script. Based on the stacktrace in the screenie below, it looks like it's line 114 as it attempts to decode the JSON object. Once a JSON object with these characters exists within our storage account, the script continues to fail until we delete the problematic blobs.

![image (3) copy](https://user-images.githubusercontent.com/72743072/225461506-c7d8453b-a3f0-4885-93f6-fff81e686090.png)

**Comment by NikTripathi** [comment]
Hi @beachfires 
We have added additional logging in the function app.

Can you please use the below URL as there WEBSITE_RUN_FROM_PACKAGE value and share the latest invocation log details from the Monitor screen?

URL:- https://github.com/Azure/Azure-Sentinel/blob/v-rucdu/CloudflareICMLogging/Solutions/Cloudflare/Data%20Connectors/CloudflareConn.zip?raw=true

![image](https://user-images.githubusercontent.com/87809732/227151971-9e8f6c4f-34bf-47aa-8a06-d02ad0df2ec5.png)

Updating the WEBSITE_RUN_FROM_PACKAGE value will show you the name of the blob which is causing the issue. Can you please to download the particular blob which is causing the error and share it with us.
It will look like below>
![decfbd36-15ff-4942-b4ba-9cd56a514b07](https://user-images.githubusercontent.com/87809732/227153210-e287c89a-a64a-4184-a73b-d377962b035b.png)

Also to unblock you please delete it from your blob so that your function continues other logs execution. Meanwhile We will investigate the blob and revert with the fix.

Please note that deleting the blob is a temporary fix to unblock you and once we provide the fix, You can reupload the deleted blob and there won't be any data loss.

Thanks.

**Comment by v-rbajaj** [comment]
Hi @beachfires, can you please provide some update?

**Comment by beachfires** [comment]
hi @v-rbajaj, I deleted this file when the original issue occurred. Can you not make out the character causing the issue from the error in the screenshot? When it happens again, I will take a copy of the file for you.

**Comment by NikTripathi** [comment]
Hi @beachfires  without the blob we won't be able to investigate the reason which is causing you the issue.
If you face this issue next time please download the blob and take a back up of it so that we can investigate it throughly.
Meanwhile I can explain you one scenario which one of our customer was facing.
They were also getting the same error as you and it was related to there blob.

we investigated the issue and found that the logs/messages is these files are having a special character NEL whose Unicode value is X85. We are using this along with other Unicode values as line separator in function app to segregate multiple logs while reading the file. So, customer just needs to update the value for lineSeparator setting under function app --> configurations --> Application settings to fix their issue.

Old Value: [\n\r\x0b\v\x0c\f\x1c\x1d\x85\x1e\u2028\u2029]+

New value: [\n\r\x0b\v\x0c\f\x1c\x1d\x1e\u2028\u2029]+

 

So, we asked the customer to add/update lineSeparator app settings under function app --> configurations by following below steps and restart the function app post saving the changes.


1. Open cloudflare function from Azure Functions

2. Goto Settings --> Configuration under Application settings look for setting named lineSeparator if does not exist add a new setting with the value mentioned above in New Value else just udpate the value for existing setting.

3. Save the changes.

4. Reupload the blob files which customer have downloaded and deleted from storage account.

5. Restart the function app.

6. Monitor the function app and see if the files are getting processed successfully.

![22c01106-911e-4665-a274-ebaa254bf83b](https://user-images.githubusercontent.com/87809732/229059955-f88b816c-a2d9-4657-9890-908a9aa710b2.png)

**Comment by v-rbajaj** [comment]
Hi @beachfires, gentle reminder, we are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days.. If we don't receive response by given date we will be close this issue.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/7576 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
