### ISSUE TITLE
Unable to add domains with a TLD that contain dashes to Threat Intelligence

### ISSUE THREAD

**Issue by young9900** [Azure/Azure-Sentinel#7617]
When I attempt to add a domain that includes dashes in the TLD, I receive [domain] is not a valid name.

**To Reproduce**
1. In Sentinel, go to Threat Intelligence
2. Click on Add New
3. Select domain-name as type
4. enter a domain that contains a - (for example: testdomain.xn--fiqz9s)

**Example**
![image](https://user-images.githubusercontent.com/82418292/226665229-699565fc-52d0-4b6e-91b5-844a710b3b2a.png)

**Comment by v-rbajaj** [comment]
Hi @young9900,  you are receiving an error message in Microsoft Sentinel that says "[domain] is not a valid name" when attempting to add a domain name to Threat Intelligence, it is because that the domain name you are trying to add is not in the correct format.

Make sure that you are entering the domain name correctly, without any typos or misspellings. The domain name should be in the format of "example.com" (without quotes), where "example" is the name of the domain and ".com" is the top-level domain extension.

To fix the domain name which you have provided in screenshot, check the below screenshot.
![image](https://user-images.githubusercontent.com/120547590/228245437-deba1097-4b88-4458-a7f3-9b1dd6e8b1f6.png)

**Comment by young9900** [comment]
This is not a .com top level domain.  .xn--fiqz9s is the top level.   see here:

https://icannwiki.org/.%E4%B8%AD%E5%9B%BD

Is what you are suggesting a work around?

**Comment by v-rbajaj** [comment]
Short answer - Yes.

A brief description for this is, it is not possible to add an ASCII top-level domain (TLD) in Microsoft Sentinel Threat Intelligence because the system only supports standard TLDs that are recognized by the Internet Assigned Numbers Authority (IANA) and are part of the public DNS infrastructure.

The use of non-standard TLDs, such as ASCII TLDs, is not recommended as they can cause compatibility issues and may not be recognized by many applications and systems.

If you are trying to monitor a specific domain that uses an ASCII TLD, you can still add the domain name to your threat intelligence data sources in Microsoft Sentinel. However, you would need to use a recognized TLD such as .com, .org, or .net instead of the ASCII TLD.
