### ISSUE TITLE
Qualys VM Detection - Run.p1 fails

### ISSUE THREAD

**Issue by happy-jo** [Azure/Azure-Sentinel#786]
## Issue
When running this function app, the RPC request fails because the "-url" is malformed and cuts off the "startDate" parameter. It looks like the "$url$($startDate.ToString('yyyy-MM-ddTHH:mm:ssZ'))" does not come together within the function app properly causing Qualys to through a "Unrecognized parameter(s): published_after" error.

## To Reproduce
1. Deploy the function app and let is run.
2. Navigate to the Application Insights for the function app
3. Click on the Failures blade
4. Click on the failure count and observe the error

## Screenshots

![image](https://user-images.githubusercontent.com/16526141/85585367-f20d2800-b60d-11ea-8160-06d819535cf3.png)

# BIG NOTE
I adjusted the ARM template to point to the correct ZIP package in a pull request, this will need to be corrected first to deploy this function app.

**Comment by preetikr** [comment]
Thanks, for the report @happy-jo 
The redirection links had to be wired for this since we merged the PR and having those links hardcoded didn't allow for validations prior to merge. I've fixed these links and now all of the redirection references should work now. We are working on deploying this data connector and make it available in Azure Sentinel portal so please be patient and you should get a ready to use page with the deploy button and everything for directly working with. That's why we don't have a ReadMe on this - the goal is to make it easy for all to access it within Azure Sentinel itself.
