### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by shipothana** [Azure/Azure-Sentinel#7932]
Hi Team,

Can you advise me on how to only exclude/ include a specific day's creation date?
For you referenced below
SecurityIncident
//| where TimeGenerated > ago(1d)
|where Severity contains "High" or Severity contains "Medium"
//| summarize count() by IncidentNumber, IncidentName, Title , Severity
| summarize count() by CreatedTime , IncidentNumber, Severity,Title
| where CreatedTime contains =="23/4/2023"

Error"Query could not be parsed at '==' on line [6,29]

Token: ==
Line: 6
Position: 29
If the issue persists, please open a support ticket. Request id: 9eda7d17-337f-480c-9113-0bcaca16759b"

**Comment by v-vdixit** [comment]
Hi @shipothana It looks like there is a syntax error in the last line of your query. Instead of using "contains ==" in the filter expression, you should use the "==" operator to compare the exact value of 'CreatedTime' with the date you want to include/exclude, here is an example for same:
SecurityIncident
| where TimeGenerated > ago(1d)
| where Severity contains "High" or Severity contains "Medium"
| summarize count() by CreatedTime, IncidentNumber, Severity, Title
| where CreatedTime == datetime(2023-04-23)

I used the "datetime" function to specify the exact date and time in the format of "yyyy-mm-ddThh:mm:ssZ". You can adjust the date and time to match the specific day you want to include/exclude, to exclude data for a specific day's creation date, you can use the "!=" operator instead of "==" in the filter expression. Hope this resolves your issue, thanks!

**Comment by v-vdixit** [comment]
Hi @shipothana to obtain results we will have to insert some sample data in 'SecurityIncident' table, thanks!

**Comment by shipothana** [comment]
Although we have the data, the outcome is not appearing
<img width="533" alt="error2" src="https://user-images.githubusercontent.com/127928822/234821493-d024d110-8117-4050-b336-f3a9fc5d48a1.png">

**Comment by v-vdixit** [comment]
Hi @shipothana, as per the data 'CreatedTime' is in format ' yyyy-mm-ddThh:mm:ssZ' and if you need to filter on a specific time range within the target date, you can update the last line of the query as:
| where startofday(CreatedTime) == datetime(2023-04-23)
'startofday()' will truncate the time component of the CreatedTime timestamp, and then compare it to the target date in the same format. Thanks!

**Comment by shipothana** [comment]
I appreciate your reply.
I can see the results now; could you provide me a KQL documents.

**Comment by v-vdixit** [comment]
I apologize, but I am not sure what specific KQL documents you are looking for, if you can provide me with more context or details I would be able to assist you further, thanks!

**Comment by shipothana** [comment]
I'd like to create advanced Sentinel dashboards; could you please assist me?

**Comment by v-vdixit** [comment]
Hi @shipothana You can find the Kusto Query Language (KQL) documentation for Microsoft Sentinel in the following link [KQL-documentation](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/sentinel/kusto-overview.md) and You can find the documentation for creating dashboards in Microsoft Sentinel in the following link [Create-Dashboards](https://docs.microsoft.com/en-us/azure/sentinel/tutorial-create-dashboards), thanks!

**Comment by v-vdixit** [comment]
Hi @shipothana Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days. If we don't receive a response we will close this issue as per our standard procedures. Thanks!

**Comment by shipothana** [comment]
Hi Team,

Sentinel incidents are not redirecting to Microsoft Defender for Office 365; what is the issue here?
 
May I know what I need to do to troubleshoot?
