### ISSUE TITLE
Carbon Black Cloud function app configuration page and function code need modification to fetch only selected log types

### ISSUE THREAD

**Issue by anki-narravula** [Azure/Azure-Sentinel#8034]
Original issue reported here: https://github.com/MicrosoftDocs/azure-docs/issues/108962

You should provide a recommended configuration.
For example, I tried to avoid using S3 buckets so I chose just 'Alert' and that won't work because your powershell script requires an S3 bucket for the Carbon Black 'SIEM' api pull.

Here's a suggested configuration that works:

![image](https://github.com/Azure/Azure-Sentinel/assets/10404181/573bc4cb-11ad-473e-9cc4-35dec9d5f987)

Documentation Page:
[https://learn.microsoft.com/en-us/azure/sentinel/data-connectors/vmware-carbon-black-cloud-using-azure-function](https://github.com/MicrosoftDocs/azure-docs/issues/url)

**Comment by v-vdixit** [comment]
We are checking on this, will update shortly, thanks!

**Comment by v-vdixit** [comment]
We are working on updating the requested changes, will update by end of this week, thanks!

**Comment by v-vdixit** [comment]
We are working on this internally, will update as soon as the changes are done, thanks!

**Comment by v-vdixit** [comment]
We are still working on UI changes, will update by end of this week, thanks!

**Comment by v-vdixit** [comment]
We are working with ARM templates and their related resources, in order to apply essential conditions in connector deploy file, thanks!

**Comment by v-vdixit** [comment]
We are working with ARM templates and their related resources, in order to apply essential conditions in connector deploy file, thanks!

**Comment by v-vdixit** [comment]
The issue requires deep knowledge of ARM templates and related resources, will take us some time to work and find details related to this, will be able to provide next update till Friday, 21st July 2023

**Comment by v-vdixit** [comment]
We are still working on these changes, will update by Friday, 21st July 2023, thanks!

**Comment by v-vdixit** [comment]
We are working on testing the updated changes, will provide update by Monday, 24th July 2023

**Comment by v-vdixit** [comment]
We still need to check on some updates on this template, will provide update by Friday, 28th July 2023, thanks!

**Comment by v-muuppugund** [comment]
We still need to check on some updates on this template, will provide update by Friday, 4th Aug 2023, thanks!

**Comment by v-muuppugund** [comment]
We are still we are working on it and will provide an update once we are done with changes.

**Comment by cwatson-cat** [comment]
[bobsyourmom](https://github.com/bobsyourmom) commented [on Jun 7](https://github.com/MicrosoftDocs/azure-docs/issues/108962#issuecomment-1580766027)
I figured it out and made a short blog/checklist for this:
[https://simple-security.ca/2023/05/02/cheat-sheet-for-configuring-carbon-black-cloud-edr-for-sentinel/](https://github.com/MicrosoftDocs/azure-docs/issues/url)

Some possible recommendations:

CB Alerts Only:
If you just need the CB alerts, then just check off 'Alert - supported with SIEM API credentials'. This is a good starting point since you don't have to worry about connecting to AWS.

CB Alerts with All Events
If you need all of the events associated with the alerts, then check off these 2:
Event - supported with aws s3 bucket credentials
Alert - supported with aws s3 bucket credentials
And then proceed to set up an s3 bucket along with everything else.

Audit
These are just basic Carbon Black audit logs, no alerts/events here.
And no need for s3 buckets so enable it with no difficulty.

**Comment by v-muuppugund** [comment]
Already function app code has logic ,so marking it as resolved
