### ISSUE TITLE
Start-MDEAutomatedInvestigation update incident after investigation finishes

### ISSUE THREAD

**Issue by ampred1ct** [Azure/Azure-Sentinel#8151]
Could you please advise how can we update incident in sentinel, after automated investigation finishes (and we have such results - **no threat s found**): 

<img width="576" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/131868616/c1b1b14e-b3bf-4915-95d6-21b5b5357a27">

if is it to be configured at security.microsoft - defender page - please advise how to configure it there
or if it is to be added any new steps in logic of the same playbook (Start-MDEAutomatedInvestigation) - could you please advise which steps to add?

**Comment by ampred1ct** [comment]
Hello r-bajaj,
many thanks for fast response. after checking:

![image](https://github.com/Azure/Azure-Sentinel/assets/131868616/1db8f302-7dc8-44d4-bb04-5c260b65df8c)

and inside incident (does not matter if old or new look experience) there is no "Automated investigations tab". 
pls see :
<img width="961" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/131868616/42d2bf7c-a27d-44c7-851c-d290f4ddda14">

moreover, in security microsoft - defender console, in this alert is updated , alert status is - resolved - but there is no update to sentinel incident. please see:
![image](https://github.com/Azure/Azure-Sentinel/assets/131868616/071fa2d0-7041-49b4-9e14-f98b7d2e46c9)


and question is how to configure it to receive 'automated closing of incident' after running automated investigation where result is no threats found.

**Comment by v-rbajaj** [comment]
Hi @ampred1ct, Thanks for sharing the screenshots, and apologize for the confusion. 
With my understanding, I think this is something you were looking for?

Well, to configure Azure Sentinel to receive an automated closing of an incident when an automated investigation concludes with no threats found, you can follow these steps:

1. In the left-hand menu, click on "Analytics" to access the Analytics page.
2. Create or edit an analytics rule that triggers the automated investigation. If you already have an existing rule, select it to edit, or click on "Create" to create a new rule.
3. In the analytics rule configuration, ensure that you have defined the appropriate logic and conditions to trigger the automated investigation when an alert or event occurs. This can include specific criteria, such as the severity of the alert or specific keywords in the event description.
4. Under the "Automation" section of the analytics rule, you can define the playbook that runs the automated investigation. Click on the "Select playbook" button.
5. In the playbook selection dialog, choose the playbook that corresponds to the automated investigation you want to run. If you need to create a new playbook, click on "Create new playbook" and follow the instructions to configure the necessary steps and actions.
6. Once you have selected or created the playbook, configure it to include the necessary steps to perform the automated investigation. This can include actions like querying logs, performing threat intelligence lookups, or running specific commands.
7. To configure the automated closing of the incident when no threats are found, you need to add additional steps to the playbook logic.
8. After the investigation steps, add a condition or action to check if threats were found during the investigation.
9. If no threats were found, add an action to update the incident status to "Resolved" or "Closed" and provide a relevant comment indicating that no threats were found.
10. Save and publish the playbook.
11. Activate the analytics rule to enable it.

With this configuration, when the analytics rule triggers an automated investigation and no threats are found, the playbook will update the incident status to indicate that it has been resolved or closed. This automated closing of the incident will help streamline the incident management process and provide an accurate representation of the investigation outcome.

Please let us know if this helped

**Comment by ampred1ct** [comment]
Hi @v-rbajaj, many thanks for reply.
Yes, you are right and my question is related mainly to point 7 and 8 from your answer. 

Question is, literally, what step has to be added to playbook logic? (I guess that there is no possibility to add step to check automated investigation status and result - no threats found, but maybe I am wrong)

Please see following possible to choose:
![image](https://github.com/Azure/Azure-Sentinel/assets/131868616/f997535c-6d74-4033-842a-6c59d88dc443)

![image](https://github.com/Azure/Azure-Sentinel/assets/131868616/7a74ac7c-07ca-49e2-87ba-b306cb438c7b)

![image](https://github.com/Azure/Azure-Sentinel/assets/131868616/e22679ce-678c-464c-ab19-cb5c3f8ae8a8)

![image](https://github.com/Azure/Azure-Sentinel/assets/131868616/48273c96-cbe2-445f-bb41-81a8064ef61e)

If You could please advise me which from following above to use to answer to points 7 and 8 ?

**Comment by v-rbajaj** [comment]
Hi @ampred1ct, we are checking with the team internally, we will soon get back to you

**Comment by v-rbajaj** [comment]
Hi @ampred1ct, can you check if there is an API for Microsoft 365 which we can use to know the status and then use that API call in playbook using request action?

**Comment by v-rbajaj** [comment]
Hi @ampred1ct, we are still trying to get in touch with the respective team who can provide us more clarity on this.

**Comment by v-vdixit** [comment]
Hi @ampred1ct we are working with the team, will update you by the end of this week, thanks!

**Comment by v-vdixit** [comment]
Hi @ampred1ct we are working with the team, will update you by the end of this week, thanks!

**Comment by v-rbajaj** [comment]
Hi @ampred1ct, we are still working on this, we will soon update you once we receive an update.

**Comment by BenjiSec** [comment]
> Hello r-bajaj, many thanks for fast response. after checking:
> 
> ![image](https://user-images.githubusercontent.com/131868616/242244952-1db8f302-7dc8-44d4-bb04-5c260b65df8c.png)
> 
> and inside incident (does not matter if old or new look experience) there is no "Automated investigations tab". pls see : <img alt="image" width="961" src="https://user-images.githubusercontent.com/131868616/242245465-42d2bf7c-a27d-44c7-851c-d290f4ddda14.png">
> 
> moreover, in security microsoft - defender console, in this alert is updated , alert status is - resolved - but there is no update to sentinel incident. please see: ![image](https://user-images.githubusercontent.com/131868616/242246160-071fa2d0-7041-49b4-9e14-f98b7d2e46c9.png)
> 
> and question is how to configure it to receive 'automated closing of incident' after running automated investigation where result is no threats found?

Hi @ampred1ct - why you do not utilize Microsoft 365 Defender connector instead of Microsoft Defender for Endpoint standalone connector? Microsoft 365 Connector have bi-directional sync of incidents/alerts, so when incident is closed in Microsoft Sentinel it is closed in Microsoft 365 Defender, and vice versa, when it is closed in Microsoft 365 Defender it is closed in Microsoft Sentinel. 
https://learn.microsoft.com/en-us/azure/sentinel/connect-microsoft-365-defender
NOTE: If enabling this connector, make sure that all Microsoft Incident Creation Rules for MDE, MDO, MDI, MDA and AAD Identity Protection (If AAD IP alerts are being synced to M365D), are turned off. This should be done automatically by enabling M365D connector. If they are not disabled, you will get double incidents - one from M365D connector (that we want) and second from Microsoft Incident Creation Rule that is not disabled.


If you don't want to utilize M365D connector, but strictly MDE connector with Microsoft Incident Creation Rule, you will need to create automation that will run on recurring event (like 5 minutes), check closed incidents/alerts in MDE in those 5 minutes (, find them in Sentinel using Azure Monitor Logs action, and update each incident in Sentinel as closed.
MDE API that you will need to utilize
https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/get-alerts?view=o365-worldwide
you will need to filter on events "status" and "resolvedTime" as you need only closed alerts that are closed in last 5 minutes for example. Then you will need to find that alert in sentinel using KQL and Azure Monitor Logs action called Run query and list results. Last step is to update Sentinel incident.
We recommend use of M365D connector as this is built in the connector itself.

**Comment by v-rbajaj** [comment]
Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/8151 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by v-rbajaj** [comment]
Hi @ampred1ct, Gentle Reminder: We are awaiting for your response on this issue. If you still need to keep this issue active please respond on it in the next 2 days . If we don't receive response, we will be close this issue.

**Comment by v-rbajaj** [comment]
Hi @ampred1ct, Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/8151 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
