### ISSUE TITLE
Logic App Failing - 404 Message on Alert-Get Incident

### ISSUE THREAD

**Issue by AudioConnoisseur** [Azure/Azure-Sentinel#8182]
I use Logic Apps to handle Incident alerting via Email.  We start with "When a response to an Azure Sentinel Alert is triggered" to kick off the Logic App.  Once that fires off, it runs three parallel steps.  "Alert - Get Incident" is one of them.  The other two are "Run query and list results", and "Run query and visualize results".  The latter two run successfully.  

The failed Get Incident function gives me this error message:

{
  "error": {
    "code": 404,
    "source": "logic-apis-eastus.azure-apim.net",
    "clientRequestId": "_Redacted_",
    "message": "The response is not in a JSON format.",
    "innerError": "Failed to run playbook - no incident found with the properties you provided"
  }
}

If I run the Logic App manually and resubmit the task, it runs successfully, but it takes about 7 seconds to complete.  It used to take under a second.  We have multiple Sentinel environments using the same logic app structure, and they all started failing in the same manner.  The are hosted separately from each other.  This same Logic App has worked for over a year without issue prior to this.

**Comment by v-vdixit** [comment]
Hi @AudioConnoisseur thanks for flagging this we will discuss with team and update you, thanks!

**Comment by v-vdixit** [comment]
Hi @AudioConnoisseur can you please share the screenshot of the logic flow steps of playbook and the output of the step right before the failing step, thanks!

**Comment by v-vdixit** [comment]
Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond on it in the next 2 days. If we don't receive response, we will be closing this issue as per our standard procedures, thanks!

**Comment by v-rbajaj** [comment]
Hi @AudioConnoisseur, Since we have not received a response in the last 5 days, we are closing your issue https://github.com/Azure/Azure-Sentinel/issues/8182 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.

**Comment by pergyz** [comment]
Regarding the "Alert - Get Incident" action failing intermittently, I suggest implementing a "do until" loop with a 1-minute delay per iteration. Personally, I have set the loop to run for 60 iterations, but this might need adjustment based on other factors, such as playbook execution time.

Regarding the availability of the incident after alert creation, it is possible that the incident may not be created immediately after the alerts are generated. Additional correlation might be performed by Defender for XDR, such as combining multiple alerts into a single multi-stage incident.

I am not using a playbook with the incident trigger because some incidents, such as multi-stage incidents, involve multiple types of alerts. The incident details include entities from different alerts, making it difficult to run playbook actions precisely based on a specific alert.

<img width="815" alt="Screenshot 2024-08-14 095026-0" src="https://github.com/user-attachments/assets/1af302e2-5bd8-44bb-a282-ecec12d29b82">
