### ISSUE TITLE
Abuse.ch Recent Threat Feed.yaml

### ISSUE THREAD

**Issue by howcanweautomatethat** [Azure/Azure-Sentinel#8251]
**Describe the bug**
When using the extended version of Abuse.ch Recent Threat Feed.yaml, you receive 10K false positives. Using the "lite" version, doesn't produce this.

**To Reproduce**
Run this KQL, 
https://github.com/Azure/Azure-Sentinel/blob/master/Hunting%20Queries/Microsoft%20365%20Defender/Campaigns/Abuse.ch%20Recent%20Threat%20Feed.yaml

**Expected behavior**
Match files only with SHA256\MD5 from recent abuse \ bazaar

**Comment by bobsyourmom** [comment]
I suspect this is happening because the abuse.ch csv file may have added in double quotes to all of the fields.
If you add in this one line it will strip out all of the double quotes and the csv file will parse correctly:
 | where report !startswith '#'
     **|extend report = replace_regex(report,@"""",@"")**
    | extend report = parse_csv(report)

I would also suggest adding a where clause to the end of this query in order to prevent it from flooding alerts in the future:
|where SHA265 <> ""

**Comment by v-vdixit** [comment]
Hi @howcanweautomatethat thanks for flagging this, we will work with the team and update you shortly, @bobsyourmom thanks for your insights, this will be helpful in finding resolution for the issue.
