### ISSUE TITLE
Maintain Synchronization of Investigation Information from Microsoft Defender for Office 365 to Azure Sentinel

### ISSUE THREAD

**Issue by paespi0** [Azure/Azure-Sentinel#8578]
**Is your feature request related to a problem? Please describe.**
I have a customer who saw this announcement today (https://learn.microsoft.com/en-us/azure/sentinel/whats-new#changes-to-microsoft-defender-for-office-365-connector-alerts-that-apply-when-disconnecting-and-reconnecting).  The issue for the customer is, Microsoft could generate an alert, run an investigation that comes back as true positive, and customer would never know (with current logic customer uses in their security solution) b/c it would never reflect in Sentinel.

**Describe the solution you'd like**
In terms of what customer would like to see, they want the investigation information (state, etc.) to continue to be synchronized into Sentinel.  As described, this change would leave customer's integration blind the current investigation status (and other information) as well as blind to any updates made to it.  Beyond the customer's integration it seems surprising that this would be acceptable to regular users who use Sentinel as their single pane of glass to manage alerts.  This leaves the only way to get status updates as pivoting to a different console (Defender 365) and periodically checking.  AIR investigations run for hours and sometimes days so how would a human manage that?

**Describe alternatives you've considered**
N/A,

**Additional context**
The article provided above, seems to indicate Microsoft is stopping providing the investigation (AIR) information in Sentinel.  If true, this is a HUGE problem for the customer.  Their integration uses this information to drive its entire lifecycle.

**Comment by v-rbajaj** [comment]
Hi @paespi0, thanks for flagging this, we will provide an update soon on this.

**Comment by v-vdixit** [comment]
Hi @paespi0 we are investigating into this, will update you by Wednesday 26th July 2023, thanks!

**Comment by v-rbajaj** [comment]
We are still investigating and trying to reach out to concerned team, we will update you once we receive a response.

**Comment by v-rbajaj** [comment]
Hi @paespi0, AIR alerts are still provided. The only thing that will change if the customer disconnects and reconnects is the “Investigation” details (name, link and status) that are not part of the alert and will be going through a change led by the MDO team and hence are not part of the alert.

**Comment by mtscher** [comment]
@v-rbajaj ... that is precisely the problem.  By removing this there is now no easy way, via API, to know if an AIR investigation is underway related to that alert, when it finishes or anything else.  Microsoft offers no API functionality related to investigations.  By making this very breaking change you are essentially removing what was the only way for integrated platforms to know this information.  Even the release notes for this change indicate that the "new" suggestion for knowing this to look in the user interface.  This change breaks integrations and offers no reasonable programmatic alternative.

**Comment by v-rbajaj** [comment]
Hi @mtscher, we will get back to you.

**Comment by v-rbajaj** [comment]
Waiting for response from response from the concerned team, we will get back to you.

**Comment by v-rbajaj** [comment]
We are reaching out to the respective teams internally and we will get back to you once there is an update.

**Comment by v-rbajaj** [comment]
Hi @paespi0, we have escalated the issue to the concerned team, we will get back to you ASAP.

**Comment by mtscher** [comment]
I see it was escalated last week and there is still no update.   This is going on 6 weeks with zero response from Microsoft in any meaningful fashion.

**Comment by prtanej** [comment]
Hi @mtscher, @paespi0 - Hear you on the end-to-end experience gap that customers will experience with this change and the additional actions required for a customer to get contextual information about the alert. We've relayed your feedback internally to MDO and Sentinel teams which will warrant some internal discussions to ensure customer experience in consuming the alerts either on Sentinel or M365D is not regressed.

This will be a non-trivial effort and will need some time to get through. We do not have an ETA on the planning and execution, but I can commit that the feedback is very much appreciated and has reached the right folks to triage and action it.

We will be closing this issue here and tracking it internally. Please feel free to re-open it if you have further questions.

Thank you.

**Comment by mtscher** [comment]
If you have closed the issue and are tracking it only internally how will we know if it is ever addressed?  I honestly interpret this as "thanks for your feedback (but nothing will change)"  It took 6 weeks to even get a "we have relayed your feedback to the appropriate group"

**Comment by prtanej** [comment]
Hi @mtscher - Apologies if it came across that way, but that wasn't the intent. The intent always was to keep the issue updated with latest developments when we had any updates about it. The issue was closed only because we currently do not have timelines on when the design discussions will commence and conclude. If you'd prefer, we can reopen it, but we do not have enough details to comment on when the next update on this will be.

I can completely understand that 6 weeks is too long for us to be able to give you clarity on where we're at with the request. Apologies for the prolonged delay on this, but we do appreciate and look forward to the feedback to continue to pivot in the direction that's most relevant for customers.
