### ISSUE TITLE
Sentinel SOC Workbook

### ISSUE THREAD

**Issue by ElancoDR** [Azure/Azure-Sentinel#8671]
It indicates the SOC workbook is installed but when you view "Templates" or "My workbooks" it is not listed. I can see it in Content Gallery

**Comment by v-sudkharat** [comment]
Hello @ElancoDR, thank you for reaching out to us, we are sharing some steps with screenshot so could you please follow once and let us know workbook are listed.
Steps :- 
 1. Save the workbook template from template tab.
 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/0737acc5-5330-493c-a589-ccf4dbc0d987)

2. After saving workbook template, refresh the page once so that content gets reflected successfully in "My Workbooks" tab.
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/89b77704-9559-4926-bd29-843a98225496)

3. Once step 2 is done, wait for few minutes and click on "View template " and "View saved workbook".

**Comment by ElancoDR** [comment]
I was able to locate it thanks.

**Comment by ElancoDR** [comment]
thanks
