### ISSUE TITLE
Logic APP "PaloAlto-PAN-OS-BlockIP" fails - Error "Could not establish trust relationship for the SSL/TLS secure channel."

### ISSUE THREAD

**Issue by secuit** [Azure/Azure-Sentinel#9034]
**Describe the bug**
The Logic App "PaloAlto-PAN-OS-BlockIP" fails in the Step 'List Address Objects' wit the Error - The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
My Palo Alto in Azure has an Self Signed Certificate. how can the http request be influenced with regard to the certificate error so that the connector works?

**Expected behavior**
Connections should be established to the palo firewall. There is no hint in the connector to deal with this problem.

**Screenshots**
<img width="620" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/57812394/d30f9868-c9a7-48ef-b796-f5842c3cb883">

**Comment by v-sudkharat** [comment]
Hi @secuit, thanks for flagging this issue, we will soon get back to you on this. Thanks!

**Comment by secuit** [comment]
Is there any update? Do you know when you can check this issue? Thanks. Sebastian

**Comment by v-sudkharat** [comment]
Hi @secuit, 
As your Palo Alto has a Self-Signed Certificate. You need to configure logic app for Standard logic app workflows and also have to complete a few extra steps for this authentication type. Otherwise, the call fails. Please refer the below screenshots and documentation. 
`https://learn.microsoft.com/en-us/azure/logic-apps/logic-apps-securing-a-logic-app?tabs=azure-portal#access-for-outbound-calls-to-other-services-and-systems`
```
TLS/SSL certificate authentication - 
https://learn.microsoft.com/en-us/azure/connectors/connectors-native-http#tlsssl-certificate-authentication
```
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/149443c7-dacc-4da1-b1a2-5fd7a6adc557)


While deploying the Standard logic app workflows, the following steps must be taken: 
Step 1. you need to configure the - `Integration Service Environment` in same resource group.  
Step 2. the checkbox for `Associate with integration service environment` should be enabled while deploying the logic app. 
note: - The ISE will be visible in the dropdown option after step 1 completed. 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/045d61c7-c491-4282-b246-6b6c898cadba)

Kindly let us know whether the above steps worked for you.
Thanks!

**Comment by v-sudkharat** [comment]
Hi @secuit, hope you are doing well. could you please have a look at above comment. Thanks!

**Comment by v-sudkharat** [comment]
Hi @secuit, Gentle Reminder: We are waiting for your response on this issue. If you still need to keep this issue active, please respond to it in the next 2 days. If we don't receive a response by 03-09-2023 date, we will be closing this issue. 		
Thanks!

**Comment by v-sudkharat** [comment]
Hi @secuit, since we have not received a response in the last 5 days, we are closing your issue #9034 as per our standard operating procedures. If you still need support for this issue, feel free to re-open at any time. Thank you for your co-operation.
