### ISSUE TITLE
Get-GeoFromIpAndTagIncident fails when more than one label is added

### ISSUE THREAD

**Issue by javiersoriano** [Azure/Azure-Sentinel#909]
**Describe the bug**
"Add labels to incident" action from the Sentinel connector fails when more than one label is added

**To Reproduce**
Deploy the playbook as is and run it against and incident with an IP entity. The playbook run fails with the following error:

```
{
  "error": {
    "code": "Conflict",
    "message": "Newer version of resource 'b6621bfb-c66e-4a09-8486-25a1019f00c3' exists. Data was not saved"
  },
  "debugInfo": "clientRequestId: 4f732416-33fd-424b-bb49-f0bbbf7a10ca"
}
```

The first label gets added correctly but it's the second one that fails. If you remove the second label from the playbook, it finishes successfully.

It seems like the "Add labels to incident" action is not updating the etag when it tries to add the second label.

**Comment by dicolanl** [comment]
@lior-tamir

**Comment by lior-tamir** [comment]
The action does support updating more then one label at the same run.
I think that the problem is that the For Each loop runs on parallel (by default). At the same time, more then one iteration is running and trying to update the same incident. By editing the For Loop to sequential, problem is solved.
@javiersoriano , can you please verify that after the change it works at your LogicApp too?
![image](https://user-images.githubusercontent.com/55202270/88955176-3bebcc80-d2a4-11ea-8f63-60508f59f251.png)

@dicolanl I'll upload a new version of the playbook with the sequential setting

**Comment by javiersoriano** [comment]
Thanks @lior-tamir ! That fixed it. I will update the logic app definition to reflect this change :)

**Comment by bobsyourmom** [comment]
I just made a logic app with about 8 Foreach and it was difficult to tell which one was causing the conflict.
So I changed them all to concurrent and that seems to have helped.
