### ISSUE TITLE
Azure Function App deployment not working

### ISSUE THREAD

**Issue by wolyslager** [Azure/Azure-Sentinel#9521]
I recently made updates to the Abnormal Security in this pull request https://github.com/Azure/Azure-Sentinel/pull/9378. The code has been merged, however it seems the deployment is broken (link [here](https://learn.microsoft.com/en-us/azure/sentinel/data-connectors/abnormalsecurity-using-azure-functions). Whenever trying to deploy via the deploy to Azure button `[![Deploy To Azure](https://aka.ms/deploytoazurebutton)](https://aka.ms/sentinel-abnormalsecurity-azuredeploy)` 
<img width="399" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/29632564/b866b0f4-a218-41a3-9413-cfb70d85a31a">
The deployment results in empty functions 
<img width="1315" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/29632564/2ddf9136-0d70-4254-b091-ff4689b8ffa0">
Looking for any support here 🙏 cc: @v-prasadboke

**Comment by wolyslager** [comment]
update: when I deploy via Visual Studio the functions do appear. The "Deploy to Azure" button is what seems to be broken.

**Comment by wolyslager** [comment]
I tested the function app by deploying it via VS code - not via the ARM template. I think the problem lies with the zip file. When I deploy via vs code, the App Files section of my function app looks fine (with the host.json file) 
<img width="264" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/29632564/e42a935c-a1a3-4a85-b568-00d8023e8a78">
However, when I deploy via the ARM template, I see this instead
<img width="785" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/29632564/94d20aaa-48f9-4d13-bf13-93189740a064">

**Comment by wolyslager** [comment]
@v-sudkharat is there another mechanism through which I can get support for this problem? Its affecting our customers and its urgent that I fix it. I understand you are probably busy with other things but if there is another medium where I can get more urgent assistance I would appreciate you directing me there :) thank you!

**Comment by wolyslager** [comment]
I think this is probably a good summary of what is happening https://superuser.com/questions/104500/what-is-macosx-folder

**Comment by v-sudkharat** [comment]
Hi @wolyslager, we apologize for the delay and greatly appreciate your understanding and cooperation. we are diligently working to reproduce and resolve the issue you've encountered.
Upon investigation, we found that the issue was due to an incorrect folder structure within the existing Zip file. We have corrected the folder structure inside the zip file and deployed the function app using the ARM template. As a result, we are now able to see the functions. 
Sharing a screenshot for your reference: 
![image](https://github.com/Azure/Azure-Sentinel/assets/132428394/c14f9e7d-ca72-43ef-8650-30271cf81ca9)

We acknowledge and appreciate your efforts for raised a PR with the necessary corrections. However, we noticed that the "_MACOSX" folder was removed in your zip file while the rest of the folder structure remained the same which needs to be corrected. We have raised a draft PR to test the function app and correct the folder structure inside zip. Could you please refer to that and make the necessary changes accordingly?

Draft PR link - https://github.com/Azure/Azure-Sentinel/pull/9547

Please let us know if the issue is still persist. 

Thanks!

**Comment by wolyslager** [comment]
@v-sudkharat thank you! I will take a look at the pr and make the necessary adjustments 🙏

**Comment by wolyslager** [comment]
Created the PR here! https://github.com/Azure/Azure-Sentinel/pull/9560
