### ISSUE TITLE
Threat Intelligence Solution latest version is not published to Content Hub

### ISSUE THREAD

**Issue by kfriede** [Azure/Azure-Sentinel#9668]
**Describe the bug**
The Threat Intelligence solution is at 3.0.2 as of a few weeks ago, but content hub still shows 3.0.1 as latest version. 3.0.2 was updated in PR #9369 and merged on 2023-12-20

**To Reproduce**
1. Go to Content Hub in Sentinel
2. Find Threat Intelligence solution
3. View version

**Expected behavior**
Expect 3.0.2 to be shown, instead 3.0.1 is shown as latest

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by v-muuppugund** [comment]
Hi @kfriede , Thanks for flagging this issue, we will investigate this issue and get back to you with some updates by 29Dec2023. Thanks!

**Comment by v-sudkharat** [comment]
Hi @kfriede, Thank you for raising this issue with us. We have checked this issue and found that, the few contents of the Threat Intelligence solution are in private preview, due to that this solution has not been rolled out yet. However, if you wish to use version 3.0.2, we would be happy to share the custom deployment steps with you. By using a custom deployment, you can access the features of the 3.0.2 solution.
Please find the custom deployment steps in attachment's- 
Main Template link - https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Threat%20Intelligence/Package/mainTemplate.json  
[Custom Deployment of the Solution.docx](https://github.com/Azure/Azure-Sentinel/files/13778563/Custom.Deployment.of.the.Solution.docx)

Thanks!

**Comment by kfriede** [comment]
Hi @v-sudkharat, could you please indicate which parts of the solution are in private preview that weren't in 3.0.1? I don't see any changes that would prevent it from being published.
