### ISSUE TITLE
unable to pass a parser

### ISSUE THREAD

**Issue by AllyDao** [Azure/Azure-Sentinel#9733]

**Comment by v-muuppugund** [comment]
@AllyDao ,As discussed over teams call on this issue,Please check this issue and let me know the issue persists of the parser
(https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Microsoft%20Exchange%20Security%20-%20Exchange%20On-Premises/Parsers/ExchangeAdminAuditLogs.yaml)

**Comment by v-sudkharat** [comment]
Hi @AllyDao, Could you please check on above comment. Thanks!

**Comment by v-muuppugund** [comment]
Hi @AllyDao, Gentle Reminder,Could you please check and let us know if issue has been resolved or not

**Comment by v-muuppugund** [comment]
Hi @AllyDao , Since we have not received a response in the last 5 days, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9733) as per our standard operating procedures. If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation
