### ISSUE TITLE
Microsoft Exchange Security Review - Online workbook fails with "The name 'ESIEnvirnonment_s' does not refer to any known column, table or function"

### ISSUE THREAD

**Issue by MatthiasScharl** [Azure/Azure-Sentinel#9757]
**Describe the bug**
Both the "Microsoft Exchange Security Review - Online" and "Microsoft Exchange Least Privilege with RBAC - Online" workbooks of the solution "Microsoft Exchange Security for Exchange Online" fails with "The name 'ESIEnvirnonment_s' does not refer to any known column, table or function"

<img width="507" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/94482111/caf62582-f5d9-4624-8480-addc3f861094">

**To Reproduce**
Installed the solution and setup the requierements.
The runbook "Start-ESICollector" job runs without errors.

<img width="585" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/94482111/64efbb8c-5669-4fde-9620-1575056054ae">

When I load the fuction ExchangeEnvironmentList it does not know about "ESIEnvironment_s"

![image](https://github.com/Azure/Azure-Sentinel/assets/94482111/f07092fa-a734-4168-b630-aa7199c24619)

The table ESIExchangeOnlineConfig_CL does not contain a column "ESIEnvironment_s"

<img width="464" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/94482111/feec48fa-6d8e-441f-ad91-06ecce7a8854">

**Comment by MatthiasScharl** [comment]
[like]  Matthias Scharl reacted to your message:
________________________________

**Comment by v-muuppugund** [comment]
Hi @MatthiasScharl ,As discussed over teams, Blocked your time tomorrow for a discussion on this issue as having queries,Please join the meeting.

**Comment by MatthiasScharl** [comment]
Hi @v-muuppugund, I did not receive any communications from you via Teams. Not sure to whom you have talked to.

**Comment by v-muuppugund** [comment]
Hi @MatthiasScharl ,Apologies for the delayed response, Could you please check the table from from the log analytics work space by following the below steps

1. Open the log Analytics work space used in automation account -->Navigate under settings->Tables->Check the Table i.e. ESIExchangeOnlineConfig_CL is Cutom table or Custom(classic),its should be custom classic table then its not editable,if its custom table we can edit column with "ESIEnvironment_s" instead of ESIEnvironment_g. 
2.Please check any data in ESIExchangeOnlineConfig_CL ,I am assuming its on first run,if no data exists then delete this table and  update the varaibles of Tenant with Tenant name from Microsoft Entra ID,please refer below screen shots for reference,
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/496b62ab-db24-41c2-a3d9-1c99792b7c41)
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/de581ed4-c305-4ea7-aa32-ef740347c1ca)

Then go Automation account ->Open Run Book->Start the job,Please refer below screen shots for reference
![image](https://github.com/Azure/Azure-Sentinel/assets/139563098/073405b3-3827-4852-906a-c13cc3d95f3d)

After the job is successful, then the table will be created in the respective log analytics with correct column as "ESIEnvironment_s"

Please let me know if you have any issues.

We have created a bug for this issue and will be working on it
https://github.com/nlepagnez/ESI-PublicContent/issues/8

**Comment by v-muuppugund** [comment]
HI @MatthiasScharl ,Gentle Reminder,Could you please check above steps and let us know if any issues.

**Comment by MatthiasScharl** [comment]
Hello @v-muuppugund. The table ESIExchangeOnlineConfig_CL in my workspace is a Custom table (classic). I have deleted it and ran the collector again. The job completes with

<img width="676" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/94482111/3108aa87-425c-4798-86f3-56297b7fb298">

but shows the following error

<img width="607" alt="image" src="https://github.com/Azure/Azure-Sentinel/assets/94482111/7a2e9618-5bd8-4e97-ae01-55d437d355a1">

The table  ESIExchangeOnlineConfig_CL was not re-created.

**Comment by v-muuppugund** [comment]
Hi @MatthiasScharl ,maximum job stream limit is 1MB i.e. A single steam job cannot be more than 1MB,Please find below link for reference
https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#automation-limits

Will investigate with detailed analysis and get back to you with an update,which command causing more size we need check,if needed we can have a teams meeting for the same.

**Comment by v-muuppugund** [comment]
Hi @MatthiasScharl , I have verified the code, but unable to replicate the issue as don't have sufficient permissions at tenant level, Could you please share couple of time slots for a team's meeting to (v-muuppugund@microsoft.com)

**Comment by v-muuppugund** [comment]
HI @MatthiasScharl ,As discussed over call,Scheduled teams meeting on monday for further trouble shooting,Please join the meeting.

**Comment by v-muuppugund** [comment]
Hi @MatthiasScharl ,As discussed yesterday over teams meeting,able to set up local environment for debugging the run book,today will have  one more session for troubleshooting the issue.

**Comment by v-muuppugund** [comment]
Hi @MatthiasScharl ,As discussed on last wednesday ,issue has fixed after local debugging from VS code and unable connect with you after wards,Please let me know when we can connect on next steps

**Comment by v-sudkharat** [comment]
Hi @MatthiasScharl, Hope you are doing well. Our team has waiting for your response on above comment. Thanks!

**Comment by v-muuppugund** [comment]
Hi @MatthiasScharl ,As discussed over teams today,will be blocking your calendar on 26/2 or 27/2 at 9:30pm IST

**Comment by v-muuppugund** [comment]
Hi @MatthiasScharl ,As discussed over team's call, the issue has been fixed, we are closing your issue (https://github.com/Azure/Azure-Sentinel/issues/9757). If you still need support for 	this issue, feel free to re-open at any time. Thank you for your co-operation!
